### ISSUE TITLE
[공통] 헤더 컬러 수정

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#1]
![image](https://user-images.githubusercontent.com/3823119/48414251-8609e300-e78d-11e8-9f17-b44fd390cac6.png)

헤더 컬러 화이트로 수정

**Comment by welaaa-sangyeon** [comment]
헤더 세로값이 현재 84dp로 잡혀있는데, 85dp로 변경 요청드립니다.

--
![image](https://user-images.githubusercontent.com/44987455/51160684-79f7ea00-18d2-11e9-8e12-eb99fbd12134.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 메뉴 아이콘이 잘못 적용된 것 같습니다.
- 컬러는 #353A3C
- 위치는 현재처럼 그대로하고 교체만 해주시면 될듯 합니다

[헤더 아이콘 3종.zip](https://github.com/smart-learning/design-2.0/files/2858751/3.zip)
(현 윌라에 적용된 아이콘입니다.)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

검색, 장바구니 아이콘 그대로입니다
