### ISSUE TITLE
[메인 > 오디오북] 새로나온 오디오북 컴포넌트 스타일 변경.

### ISSUE THREAD

**Issue by daroong2** [smart-learning/design-2.0#102]
앱 디자인 참고하여 스타일 수정.

**Comment by daroong2** [comment]
<img width="193" alt="welaaa 2018-12-14 10-51-06" src="https://user-images.githubusercontent.com/29753306/49978518-469e0480-ff8e-11e8-856f-94ecc1daae91.png">

컴포넌트 내부 텍스트가 데이터의 `subtitle`인데 `subtitle`의 값이 빈값(`""`)인 경우 `memo_top`을 사용하였습니다.
혹시 문제가 된다면 말씀해주시길 바랍니다.

**Comment by welaaa-sangyeon** [comment]
컴포넌트 안의 상하 간격들 재확인
 ㄴ 책과 텍스트 사이, 상하단 여백 

![image](https://user-images.githubusercontent.com/44987455/50870174-41e83700-13fa-11e9-9356-e5ff12ee6336.png)
