### ISSUE TITLE
[메인 > 클래스] 추천시리즈 스와이퍼 교체

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#104]
![image](https://user-images.githubusercontent.com/3823119/50051284-8b729880-0152-11e9-9e03-2109411fd3db.png)

**Comment by Unk** [comment]
이전 미팅때도 공유해드린 내용과 같이 추천 시리즈에 사용하는 UI의 경우 유료 라이브러리 중에서도 원하는 동작에 맞는 라이브러리는 없었고, 다행히 오픈소스 라이브러리 중 https://github.com/archriss/react-native-snap-carousel 를 발견하여 해당 라이브러리를 적용코자 합니다.

'오늘 책 한권' 메뉴와 같은 카루셀을 적용해

https://youtu.be/Q2_OtJlhj4g

와 같은 형태로 작업하면 어떨까 합니다.

**Comment by welaaa-heejae** [comment]
넵 확인하였고, 이대로 진행 부탁드려요!

**Comment by jungon-influential** [comment]
내비게이션 안정화로 인해 어떤 이슈가 발생할 지 몰라 현재는 조심스러운 입장입니다.
내부 검토 진행하도록 하겠습니다.

**Comment by welaaa-heejae** [comment]
일단 트랜지션 관련 효과는 금번 작업에서 제외해주세요. 개발상 리스크가 존재하기도 하고, 작업 속도에 영향을 미칠수 있으므로 해당 기능은 제외하고 작업 진행했으면 합니다.

**Comment by Unk** [comment]
네 알겠습니다. 😄
감사합니다.

**Comment by welaaa-sangyeon** [comment]
첨부파일 이미지로 교체 요청드립니다.
순서는 현 윌라닷컴을 참고해주세요.

[추천시리즈 썸네일 모음_190109.zip](https://github.com/smart-learning/design-2.0/files/2739051/_190109.zip)

**Comment by nanuruya** [comment]
아직 새로운 API 연결이 되어있지 않습니다. 
연결 후 다시 확인이 필요한 부분입니다. 
* 시리즈 표시 순서와 썸네일 이미지에 관련된 내용은 API 에서 함께 확인이 필요할것으로 보입니다.

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52046432-0f110900-258a-11e9-8884-a449fd852861.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

@jungon-influential 
추천시리즈 하단 두줄 문구 추가

![_](https://user-images.githubusercontent.com/44987455/52713121-d1749d00-2fd9-11e9-8680-0eb81933a012.png)

**Comment by jungon-influential** [comment]
@Unk `https://api-prod.welaaa.com/api/v1.1/cms/main/series

**Comment by jungon-influential** [comment]
@shj7831 "두 줄의 문구가 추가될 경우 이러한 위치에 들어갑니다." 에 해당하는 문구 요청 드립니다.
현재 DB에 임의 값이 들어가 있습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
