### ISSUE TITLE
[추천시리즈] 목록 페이지 추가

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#105]
![image](https://user-images.githubusercontent.com/3823119/50051291-a2b18600-0152-11e9-8e55-ae3980ddb6d7.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52711784-054dc380-2fd6-11e9-93e6-09aa50537511.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

그림자 구현 관련하여 슬랙 메시지 참고 부탁드립니다.
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550149406083300

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
