### ISSUE TITLE
[추천시리즈] 상세 페이지 추가 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#106]
![image](https://user-images.githubusercontent.com/3823119/50051292-ae9d4800-0152-11e9-8094-5ddfceed4870.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52711827-28787300-2fd6-11e9-8a43-d4f7a25505f3.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

최상단 GNB 영역은 디자인 원본처럼 이미지가 보이게 구현하기는 힘든건가요?
해당 부분이 무조건 있어야한다고 이전에 듣긴 했었는데 확인 한번 부탁드립니다.

**Comment by Unk** [comment]
네 전에 말씀드린대로 디자인처럼 구현하기는 어려울 것 같습니다.

**Comment by welaaa-sangyeon** [comment]
네 그럼 최상단 이미지에 가로 양쪽 여백에 1dp정도 여백이 보이는데 꽉차게만 부탁드릴게요
