### ISSUE TITLE
[API] `/api/v1.0/contents/video-series` 윌라 추천시리즈 api 수정 요청 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#110]
추천시리즈 디자인 변경 되면서 `/api/v1.0/contents/video-series` 에 필요한 정보 업데이트 요청드립니다. 

현재 api 에서 보내주는 데이터구조는 아래와 같습니다.
```
[
  {
    "bg_color": "#ededed",
    "category": "036",
    "item": [{},{},...],
    "title": "대한민국 명강을 만나다"
  },
  ...
]
```
요청 드리는 데이터 구조는 아래와 같습니다. 
```
[
  {
    "bg_color": "#ededed",
    "category": "036",
    "item": [{},{},...],
    "title": "대한민국 명강을 만나다"
    "headline": "카드 하단에 들어갈 2줄 문구"
    "image": "카드 썸네일로 사용될 이미지",
    "paragraph": "윌라 추천 시리즈 상세에 들어갈 소개 문구"
  },
  ...
]
```
아래 이미지는 참고용으로 첨부합니다. 
![image](https://user-images.githubusercontent.com/3823119/50505662-5f430a00-0ab8-11e9-8496-18442f3938d3.png)
![image](https://user-images.githubusercontent.com/3823119/50505696-8568aa00-0ab8-11e9-944a-beb828aa91d2.png)

확인 후 업데이트 부탁드립니다 :)
감사합니다.

**Comment by jungon-influential** [comment]
내부에서도 디자인 검토 하고 수정내용 파악 일정 산출 중에 있습니다.
원하시는 형태를 남겨주셔서 빠른 진행이 가능할 듯 합니다.
감사합니다.

**Comment by welaaa-heejae** [comment]
관련부서에 해당 내용 요청해놓았고, 받는대로 공유드릴께요.

**Comment by daroong2** [comment]
앱과 모바일에서 사용될 카드 썸네일 이미지는 데스크탑 뷰에서는 적절하지 않을 것 같아 데스크탑용 이미지를 추가적으로 요청드립니다.

추가로 요청 드리는 데이터 구조는 아래와 같습니다.

```
[
  {
    "bg_color": "#ededed",
    "category": "036",
    "item": [{},{},...],
    "title": "대한민국 명강을 만나다"
    "headline": "카드 하단에 들어갈 2줄 문구"
    "image": {
        "card": "https://static.welaaa.co.kr/static...",
        "wide": "https://static.welaaa.co.kr/static...",
     },
    "paragraph": "윌라 추천 시리즈 상세에 들어갈 소개 문구"
  },
  ...
]
```

배경색과 분리되지 않도록 card에서 쓰이는 이미지와는 달리 그라데이션 효과가 없는 이미지로 부탁드립니다.

아래의 이미지는 참고용입니다.
<img width="1016" alt="welaaa_series_detail" src="https://user-images.githubusercontent.com/29753306/50547221-58afc080-0c79-11e9-984a-72a7afdd2791.png">

**Comment by jungon-influential** [comment]
`http://api-prod.welaaa.com/api/v1.1/cms/main/series`
headline 에 해당하는 값: **title**
[
  ...
  {
    "category": "031",
    "image": "http://static.welaaa.co.kr/static/cbanner/190104_series_031.jpg",
    **"title"**: "두줄의 문구가 추가될 경우 이러한 위치에 들어갑니다."
  },
  ...
]

---

`http://api-prod.welaaa.com/api/v1.0/contents/video-series/031`
paragraph 에 해당하는 값: **paragraph**
{
  "item": [
    ...
  ],
  "series": {
    "ccode": "031",
    **"paragraph"**: "개념에서 실무까지! 윌라 마케팅 MBA",
    "id": 90,
    "image": "http://static.welaaa.co.kr/static/cbanner/190104_series_031.jpg",
    "title": "개념에서 실무까지! 윌라 마케팅 MBA"
  }
}

---

금일 17시 이전에 배포 하겠습니다.

감사합니다.

**Comment by nanuruya** [comment]
수정된 이슈입니다. 클로즈 합니다.
