### ISSUE TITLE
[메인] 멤버십 가입 권장 배너 추가

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#112]
하단 이미지 적용 후 상 하단에 흰 여백이 있는지 체크

![-](https://user-images.githubusercontent.com/44987455/50868679-f2067180-13f3-11e9-8201-97d9da1478b7.png)

**Comment by welaaa-sangyeon** [comment]
이미지 변경, 현재 앱처럼 윌라 영상 플레이

(App_class_메인페이지_190115_confirm.xd)

--
배너 이미지
![main_wide_banner_190109](https://user-images.githubusercontent.com/44987455/51160202-4e740000-18d0-11e9-8bac-c04f360734f5.png)

--
메인(클래스) - 배너 위치
![image](https://user-images.githubusercontent.com/44987455/51160407-22a54a00-18d1-11e9-8f08-9a75258f6b3c.png)

![image](https://user-images.githubusercontent.com/44987455/51160420-2f29a280-18d1-11e9-8899-6b9028ceb672.png)


--
메인(오디오북) 
![image](https://user-images.githubusercontent.com/44987455/51160479-7b74e280-18d1-11e9-9e09-a0ed404f5841.png)

![image](https://user-images.githubusercontent.com/44987455/51160509-9a737480-18d1-11e9-8f73-a26d4a12f5ba.png)

**Comment by welaaa-sangyeon** [comment]
이미지 교체

--
![default](https://user-images.githubusercontent.com/44987455/52046016-1257c500-2589-11e9-9280-f1eed4254790.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.
## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)
