### ISSUE TITLE
[메인] 윌라 프리미엄 클래스, 윌라 오디오북 레이아웃 조정

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#113]
**좌측 여백에 대한 부분은 '윌라 오디오북'에도 동일 적용**

5-1. ‘윌라 프리미엄 클래스'의 좌측 여백과
        ‘새로 나온 클래스’, ‘오늘의 인기 클래스'의 좌측 여백은 다름

![image](https://user-images.githubusercontent.com/44987455/50869184-4e6a9080-13f6-11e9-8f7d-3bdcee931e56.png)
![image](https://user-images.githubusercontent.com/44987455/50870089-f9307e00-13f9-11e9-8c18-cbc125fb24e0.png)

--
5-2. ‘윌라 프리미엄 클래스’와 컴포넌트의 좌측 간격은 같습니다.

![image](https://user-images.githubusercontent.com/44987455/50869232-7b1ea800-13f6-11e9-867b-219cf413bca1.png)

**Comment by nanuruya** [comment]
5-1. ‘윌라 프리미엄 클래스'의 좌측 여백과
‘새로 나온 클래스’, ‘오늘의 인기 클래스'의 `좌측 여백은 다름` 
-> 여백이 달라야 한다는 수정사항인가요? 

5-2. ‘윌라 프리미엄 클래스’와 컴포넌트의 좌측 간격은 같습니다.
-> 좌측간격이 같다는 부분에 대해 추가적인 설명 부탁드립니다.

**Comment by welaaa-sangyeon** [comment]
아래 이미지로 충분한 설명이 될지 모르겠지만, 각각 여백과 간격에 대한 설명입니다.
수치만 같고 다름을  봐주시면 될것 같습니다.

![image](https://user-images.githubusercontent.com/44987455/50879446-4aeaff80-141e-11e9-98c7-08424fd2bd1e.png)

**Comment by nanuruya** [comment]
정리 감사합니다. 왼쪽 선 맞춰서 수정하겠습니다.

**Comment by welaaa-sangyeon** [comment]
> [welaaa-1.50.047-2019-01-23-1833-design-release.apk] 기준

- 이부분 수정되지 않았습니다.

최종 전달 XD ‘App_class_메인페이지_190115_confirm2.xd’

--
![image](https://user-images.githubusercontent.com/44987455/51665066-43bb1880-1ffe-11e9-81a3-0856e00f560a.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk

메인 > 오디오북도 동일

--
![default](https://user-images.githubusercontent.com/44987455/52046599-775fea80-258a-11e9-943f-3e8f59e84a13.png)
