### ISSUE TITLE
[메인 > 클래스] 추천 클래스 문구 변경

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#114]
OOO님의 추천 클래스 > OOO님**을 위한** 추천 클래스
 ㄴ 비회원일 경우 ‘윌라 고객님을 위한 추천 클래스' (오디오북 동일)

--
오디오북 페이지 처럼 영역분리를 위한 라인 추가
![image](https://user-images.githubusercontent.com/44987455/50869906-5546d280-13f9-11e9-81c3-814558975904.png)

**Comment by nanuruya** [comment]
우선 비회원일 경우를 문구 표시를 다르게 하는 작업 추가 가능합니다.
문의드리고 싶은점은 현재 서비스 정책이 비회원은 메인 페이지 진입이 안되는 정책으로 알고있습니다.  
혹시 `모바일 웹`에 해당하는 이슈를 발행하신건지, 이후 정책이 변경되는것에 대비하는것인지 확인 부탁드립니다.

**Comment by nanuruya** [comment]
네 확인했습니다.
