### ISSUE TITLE
[메인] Footer (푸터) 추가

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#115]
푸터 추가  (기존시안 참고)

**Comment by nanuruya** [comment]
전달받은 xd 파일이 많기때문에 기존 시안 참고라는게 어떤 파일인지 표기 부탁드립니다.
`(예: 윌라app_클래스메인_190104.xd 시안 참고)`

**Comment by welaaa-sangyeon** [comment]
메인 페이지인 메인>클래스, 메인>오디오북 페이지 최하단에 푸터가 들어갑니다.
처음 드렸던 xd와 마지막에 드렸던 xd에서도 계속 똑같이 유지되었던 영역입니다. (내용도 같습니다.)

윌라app_클래스메인_190104.xd 파일과 윌라app_오디오북메인_190104.xd 를 확인해주세요.

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준 

--
![default](https://user-images.githubusercontent.com/44987455/52047105-aa56ae00-258b-11e9-8f1e-dd0fd98756cf.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.
## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- '(주)인플루~ 문태진' 볼드처리 빼주세요

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
일부 텍스트 삭제
- 주소:(06040)서울~ > 주소: 서울특별시~ 
    ㄴ 번호 삭제

![image](https://user-images.githubusercontent.com/44987455/52850055-e9712b80-3155-11e9-9e08-34f7bb507e2d.png)

**Comment by Unk** [comment]
`Footer.js:39` 입니다. @jungon-influential

**Comment by hyunggoo-kang** [comment]
@welaaa-sangyeon 아직 이슈가 남아있는게 있나요?

**Comment by welaaa-sangyeon** [comment]
@hyunggoo-kang 아뇨, 이슈없어 닫도록 하겠습니다.
