### ISSUE TITLE
[메인] sticky 메뉴 영역

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#116]
스크롤시 유지되는 sticky 메뉴 영역입니다.
**클래스 I  오디오북** 

(App_class_메인페이지_190108.xd)

![image](https://user-images.githubusercontent.com/44987455/50879845-b84b6000-141f-11e9-8e04-269738298be9.png)

**Comment by nanuruya** [comment]
현재 스크롤시 유지되고있습니다. 
추가적인 동작이 필요하신 부분이 있다면 설명 부탁드립니다.

**Comment by welaaa-sangyeon** [comment]
내용을 덜 썻네요, 아래 내용도 확인부탁드립니다.

![image](https://user-images.githubusercontent.com/44987455/50881771-05323500-1426-11e9-80ec-2e1f3c09b2c9.png)

**Comment by Unk** [comment]
스크롤 되면서 특정 위치에서 스티키+형태 변환 하는 걸로 이해가 됩니다.
기존의 이미지 스와이퍼 이슈와 비슷하게, 상용소스와 오픈소스를 찾아서 붙여봐야 할 것으로 생각됩니다.
직접 개발을 하기엔 너무 규모가 큰 작업이라 디자인 업데이트에 포함시키기도 어렵고, 해당 모듈 개발하는데에만 시간이 상당히 필요할테니 오픈 예정일 내에 작업이 어려울 것으로 보입니다.

overflow wrapping 형태에서 스와이프로 전환되는 부분을 자연스럽게 처리하는 부분이 혹시 참고하신 샘플이 있으시다면 공유 부탁드립니다.

혹은 디자인 업데이트가 아닌 기능 개선/혹은 기능 신규 개발의 영역으로 가야 하니 디자인 개선 프로젝트 이후에 추가 업데이트로 진행하시는 것도 내부에서 고려해보심이 좋겠습니다.

**Comment by welaaa-heejae** [comment]
네. 해당 부분은 저희쪽 개발팀에서 서포트를 구해야 할 듯하며, 관련 논의는 내일 진행할 예정입니다.
이에, 현재는 이런 이슈가 있다..정도로만 참고해주시고 내일 관련하여 다시 코멘트 드리도록 하겠습니다.

**Comment by welaaa-sangyeon** [comment]
sticky 메뉴

(App_class_메인페이지_190115_confirm.xd)

--
스크롤 전
![image](https://user-images.githubusercontent.com/44987455/51159904-c2150d80-18ce-11e9-96c2-008b08aff0b0.png)

--
스크롤 예시
![image](https://user-images.githubusercontent.com/44987455/51160006-3d76bf00-18cf-11e9-9275-c49719f3a467.png)

**Comment by Unk** [comment]
![image](https://user-images.githubusercontent.com/2232142/51160106-cdb50400-18cf-11e9-94a6-fbe6135e00d3.png)

메인 페이지의 영역은 분홍색 `컨텐츠 영역` 까지입니다.  
그 위쪽의 녹색 영역은 메인 페이지의 바깥쪽 영역입니다.  
녹색 영역까지 스크롤시 제어하기 위해서는 앱의 전체 구조 자체를 변경해야 가능하기 때문에,  
지금은 분홍색 영역 안에서만 스티키 처리가 가능하도록 작업할 수 있을 것 같습니다.

**Comment by nanuruya** [comment]
@welaaa-heejae / 해당 스티키 표시는 웹에서도 동일하게 적용되는건가요?

**Comment by welaaa-sangyeon** [comment]
슬랙으로 답변된 사항이라 혼돈을 막기위해 내용 캡쳐하여 올려둡니다.

![image](https://user-images.githubusercontent.com/44987455/51239818-b5231780-19bd-11e9-8b15-2604f12fc72a.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![1](https://user-images.githubusercontent.com/44987455/52045909-d7ee2800-2588-11e9-9930-2cd1b603b96f.png)

![2](https://user-images.githubusercontent.com/44987455/52045911-d886be80-2588-11e9-8d3c-5c36df493505.png)

![3](https://user-images.githubusercontent.com/44987455/52045912-d886be80-2588-11e9-8e5f-320f3e7501e8.png)

![4](https://user-images.githubusercontent.com/44987455/52045913-d91f5500-2588-11e9-8772-0293458eea5e.png)

![5](https://user-images.githubusercontent.com/44987455/52045914-d91f5500-2588-11e9-8987-a6cf09f97794.png)

**Comment by Unk** [comment]
`오늘의 인기 클래스`는 카테고리별로 데이터를 불러오는 API가 없습니다.
카테고리 구분 없이 불러오는 `/api/v1.0/contents/video-clips/realtime-chart` API 만 존재합니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.
카테고리 선택시 오늘의 인기 클래스/인기 오디오북 내용 변경되는 부분은 
(https://github.com/smart-learning/design-2.0/issues/116#issuecomment-459283996)
코멘트 확인 부탁드립니다. 

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by jungon-influential** [comment]
@Unk `https://github.com/smart-learning/design-2.0/issues/128#issue-401203323` 첫번째 항목 검토 하시고 부족한 부분 있으시면 말씀해주세요.

**Comment by Unk** [comment]
오늘의 인기 클래스를 카테고리별로 불러오는 부분에 대해서 말씀하시는 건가요?

**Comment by jungon-influential** [comment]
네 API 가 없다고 코멘트 주셔서 답변 드립니다.

**Comment by Unk** [comment]
현재 요청사항대로라면 `/api/v1.0/contents/video-clips/realtime-chart` 에 대한 부분도 `/api/v1.0/contents/video-clips/realtime-chart/{category}` 형식으로 API가 필요합니다.

**Comment by jungon-influential** [comment]
현재 앱에서는 `/api/v1.0/contents/video-clips/realtime-chart` 사용하고 있지 않습니다. 내부에서 애기를 해 봤는데 `오늘의 인기 클래스` 는 제공해드린 API 에서 `hot` 을 사용하시면 됩니다. 말씀하신 API 는 이름에 보이듯이 클래스도 아니고 클립이구요. 혹시 따로 전달 받으신 내용이 있으시면 말씀해주세요.

**Comment by Unk** [comment]
아, 네. 저희가 오해하고 작업한 부분이 있었네요.
오늘의 인기 클래스에 `hot` 부분 적용하는 걸로 업데이트 하도록 하겠습니다.

**Comment by jungon-influential** [comment]
넵 감사합니다.

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

1. 버튼이 잘 안눌리는 경우가 있음
2. 최상단에 위치 시 좌우 스크롤이 안되는 경우 발생 (기기별 상이함)

**Comment by Unk** [comment]
오늘의 인기 클래스, 오늘의 인기 오디오북 데이터 연결 수정

`welaaa-1.50.050-2019-02-08-0915-design-release.apk`  
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549585112015800

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_ 1](https://user-images.githubusercontent.com/44987455/52710385-873bed80-2fd2-11e9-9689-7decd509a188.png)

![_ 2](https://user-images.githubusercontent.com/44987455/52710394-8a36de00-2fd2-11e9-9387-110f16f33922.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
