### ISSUE TITLE
[메인] 스크롤 시 앵커 삽입

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#117]
체크된 영역 스크롤시 앵커 삽입

--
클래스
![image](https://user-images.githubusercontent.com/44987455/50881131-095d5300-1424-11e9-906a-fa76c3d8b087.png)

--
오디오북
![image](https://user-images.githubusercontent.com/44987455/50881201-3f9ad280-1424-11e9-8bdd-ba20e3faa8ac.png)

**Comment by welaaa-sangyeon** [comment]
ㄷㄱ









--
메인(클래스)

![image](https://user-images.githubusercontent.com/44987455/51162967-7e74d080-18db-11e9-84e1-f7eb6073e89d.png)

--
메인(오디오북)

**Comment by Unk** [comment]
개발에서 사용하는 것과 용어 차이가 있는 것 같아서 문의 드립니다. 말씀하시는 앵커가 어떤 걸 말씀하시는 건가요?

**Comment by jungon-influential** [comment]
스크롤 중에 디자인 상의 앵커 영역이 상단에 걸리도록 구현 해 주실 수 있으신가요?

**Comment by Unk** [comment]
지금 저희가 사용하는 ScrollView 자체에는 없는 기능이고, 플러그인 등이 있을지 한번 리서치를 해보겠습니다.

**Comment by jungon-influential** [comment]
제가 설명을 오해하시게 한 듯 한데 스티키 같은 걸리는 게 아니라 정지하면 됩니다.

**Comment by welaaa-sangyeon** [comment]
해당 이슈는 개발하지 않는 것으로 확정되었습니다
