### ISSUE TITLE
[메인 > 클래스 > 상세 페이지] 상단 영역 (정보,목차 윗부분) UI 수정

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#118]
기존에 작업은 해주시고 계시지만 이슈에 등록되지 않은 것 같아 올려두겠습니다.

클래스 상세페이지 상단 UI 변경

(App_class_상세페이지_190108.xd)

--
기본 

<img width="619" alt="2019-01-09 4 15 49" src="https://user-images.githubusercontent.com/44987455/50882956-e0d85780-1429-11e9-9393-03eedb871646.png">

--
클래스 타이틀 두줄이 될 경우

<img width="374" alt="2019-01-09 4 17 43" src="https://user-images.githubusercontent.com/44987455/50883021-1e3ce500-142a-11e9-8bbe-73acd45cc187.png">

--
가격할인 예시

<img width="370" alt="2019-01-09 4 18 02" src="https://user-images.githubusercontent.com/44987455/50883054-36146900-142a-11e9-9aef-3c071a90f47a.png">

--
구매 후 방문시 노출 정보

<img width="371" alt="2019-01-09 4 18 45" src="https://user-images.githubusercontent.com/44987455/50883079-4a586600-142a-11e9-951d-d312d2c06da4.png">

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

1. 구매 정책별 노출 내용 재확인 필요
2. 정책별 폰트 사이즈 확인
3. 구매 버튼 반응 없음

App_class_상세페이지_구매정책_190116.xd 참고

**Comment by Unk** [comment]
몇몇 조건에서 구매 버튼에 동작 유실된 내용 복원

`welaaa-1.50.050-2019-02-08-0915-design-release.apk`  
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549585112015800

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![1](https://user-images.githubusercontent.com/44987455/52713616-206f0200-2fdb-11e9-8fc6-844082d3cd46.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
