### ISSUE TITLE
[메인 > 클래스 > 상세 페이지] 클래스 정보 (소개카드,클래스 소개,강사 소개)

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#119]
기존에 작업은 해주시고 계시지만 이슈에 등록되지 않은 것 같아 올려두겠습니다.

클래스 상세페이지 '클래스 정보' UI 변경

(App_class_상세페이지_190108.xd)

--
기본

<img width="400" alt="2019-01-09 4 27 38" src="https://user-images.githubusercontent.com/44987455/50883468-804a1a00-142b-11e9-9e5e-8f273e63c8c5.png">

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![2](https://user-images.githubusercontent.com/44987455/52047301-0cafae80-258c-11e9-89d3-00202fcebd11.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-04-2126-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-04-2126-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549283669050600)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk

X개 의 강의 > X개의 강의 (붙여 쓰기)

**Comment by Unk** [comment]
`welaaa-1.50.050-2019-02-08-0915-design-release.apk`  
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549585112015800

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![2](https://user-images.githubusercontent.com/44987455/52713647-3aa8e000-2fdb-11e9-8622-e390bd4c8cef.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
