### ISSUE TITLE
[메인 > 클래스 > 상세 페이지] 목차

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#120]
기존에 작업은 해주시고 계시지만 이슈에 등록되지 않은 것 같아 올려두겠습니다.

클래스 상세페이지 '목차' UI 변경

(App_class_상세페이지_190108.xd)

--
기본

<img width="383" alt="2019-01-09 4 30 01" src="https://user-images.githubusercontent.com/44987455/50883679-1d0cb780-142c-11e9-97e8-c9dd472cc4b7.png">

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-04-2126-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-04-2126-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549283669050600)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

목차 하단 컴포넌트 썸네일 이미지 짤려보입니다.

**Comment by Unk** [comment]
확인해보겠습니다.

**Comment by welaaa-sangyeon** [comment]
목차 내 썸네일 밀려보입니다.
필수적으로 수정 부탁드립니다.

**Comment by Unk** [comment]
수정되어 PR 보냈습니다

**Comment by jungon-influential** [comment]
감사합니다.
