### ISSUE TITLE
[문의] `매일 책 한권` 컨텐츠 표시 관련 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#121]
안녕하세요.
`매일 책 한권` 컨텐츠 표시 관련해서 문의가 있습니다.

지난 12월 12일 미팅당시 `매일 책 한권` 이미지 처리를 텍스트 영역을 제외하고 통 이미지로 처리 하기로 협의 했었습니다. 

그런데 전달받은 `/v1.1/cms/main/a-book-a-day` API 에서는 책 이미지와 카드 이미지가 따로 처리되어있습니다. 
![image](https://user-images.githubusercontent.com/3823119/51022462-a0164500-15c7-11e9-9c36-207ac5a0cf47.png)
왼쪽 이미지 처럼 전달되는 형태가 아닌 오른쪽 이미지 처럼 전달되어야할것같은데, 
저희가 처음 잘못 이해한것인지 아니면 API 수정이 필요한지 확인 부탁드립니다.

감사합니다.

**Comment by welaaa-heejae** [comment]
죄송하지만, 해당 부분은 디자인이 많이 변경됩니다. 이에 기존 보내드린 시안은 무시하고 잠시후에 드리는 파일 참고해주심 좋을 듯 합니다.

**Comment by nanuruya** [comment]
변경이 자주 발생한다면 더더욱 책 이미지까지 통이미지에 포함해서 API 로 보내주시는게 좋을것 같습니다. 
책 이미지를 포함하는 작업은 따로 API 구조 변경 없이 이미지 교체만 하면 처리 가능합니다.

**Comment by nanuruya** [comment]
## XD 버전
App_audio_메인페이지_190115_confirm.xd

## 문의 내용
![image](https://user-images.githubusercontent.com/3823119/51160213-5a5fc200-18d0-11e9-800f-7be64f0d9d7d.png)

1. 변경된 매일 책 한권 에서는 스와이프가 없이 오늘의 책 한권만 표시되는것으로 변경된건지 궁금합니다. 
2. `‘매일 책 한권 보러가기’ 버튼 클릭시 카테고리 메뉴 중 ‘매일 책 한권(구 북리뷰)’ 페이지로 이동` 는 보내주신 xd 파일 중 `윌라app_오디오북-매일책한권_상세 페이지_190104. xd` 를 의미하는건지 궁금합니다.  
3. 변경된 매일 책 한권 상세 페이지의 API작업 전 더미 Json을 먼저 제공해주시면 좋겠습니다.

**Comment by Unk** [comment]
3번 관련해서 보충 설명 드립니다.

일전에 다른 페이지의 경우 저희가 예상되는 json 데이터 스키마를 작업해서 전달 드렸는데, 실제 api 수급 후 확인해보니 형태가 달랐습니다. 아마 서버쪽 데이터베이스의 스키마를 기준으로 출력을 하셔야 할테니 그런 차이가 발생한 것으로 생각하고 있습니다.

다만 해당 영역의 경우 변경된 데이터에 맞춰서 저희가 데이터 연결 작업을 다시 진행했기 때문에, 재작업 공수를 줄이기 위해 서버에서 주실 수 있는 형태의 목업 json 을 하나 만들어주시면 저희가 그 데이터에 맞춰서 작업을 해놓으려고 합니다. @jungon-influential

**Comment by jungon-influential** [comment]
3번 사항 확인했습니다.
가능한 빨리 작업해서 드리겠지만 선작업 하실 경우도 생길거라 예상합니다.
이전 처럼 먼저 공유 해 주시면 제가 확인해서 키를 맞춰서 드리도록 하겠습니다.
@Unk
