### ISSUE TITLE
[메인 > 클래스 > 상세 페이지] 클래스 정보 (평가,리뷰 남기기)

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#123]
리뷰 부분 UI

(App_class_상세페이지_190115_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51177872-3e761380-1904-11e9-94fe-8596a7a254a3.png)

**Comment by welaaa-sangyeon** [comment]
오디오북과 UI가 같습니다.

(App_audio_상세페이지_190116_confirm.xd)

**Comment by shj7831** [comment]
@jungon-influential 

이름 또는 아이디 중간에 잘리고 * 으로 표기될 수 있도록 하는 부분 
-> 기존처럼 이름 혹은 아이디에 암호화 처리 하지 않는 방향으로 바뀌었으므로 참고 부탁드립니다

EX) 손희* -> 손희정

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![3](https://user-images.githubusercontent.com/44987455/52047368-32d54e80-258c-11e9-8afe-f42ba0f0bcd3.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-04-2126-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-04-2126-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549283669050600)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

덧글 입력 안됨
(그 외 확인 완료)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 작성한 리뷰는 삭제가 아니라 수정이 되어야 합니다.
- 더보기 버튼 구현 요청: 리뷰를 처음에는 5개 보여주시고, 더보기를 누르면 전체를 펼쳐줍니다.
- 처음보낸 디자인에 잘못된 것이 있는데 아래와 같이 정정합니다. (본인이 리뷰를 남겼는데 최하단부에 텍스트 입력창이 있는것)

![image](https://user-images.githubusercontent.com/44987455/52692155-71183800-2fa6-11e9-8024-bf4366a78614.png)

**Comment by Unk** [comment]
* 이미 리뷰한 페이지에 댓글 입력창이 없는 부분은 처리 되어 있습니다.


* 수정 모드로 들어갈 경우 어떤 형태로 UI가 처리되는지에 대한 가이드나 디자인이 필요합니다.
* 댓글의 경우 처음부터 전체 데이터가 오고 더보기 형태로 페이징을 하도록 만들어져 있지 않습니다.
* 댓글 수정 API의 경우 swagger ui 문서상에는 존재하나 실제 호출시 405 에러가 발생합니다.

**Comment by jungon-influential** [comment]
- 댓글 페이징
  - queryparam: page, count 추가 되었습니다.
  - 내 댓글은 페이징 처리 없습니다.

- 댓글 수정
`PUT https://api-prod.welaaa.com/api/v1.0/action/comments/1280`
메소드 PUT 으로 변경 되었습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

수정모드 관련하여 가이드나 디자인이 오지않아 임의로 작업하였습니다. 

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

수정모드 관련하여 최상단에 있는 이미지처럼 이미 작업해주셔서 어떤부분의 가이드 빠뜨렸는지 모르겠습니다.

- 수정 시 우측 버튼의 '등록중'을 '등록' 으로 바꿔주세요

**Comment by Unk** [comment]
수정 버튼 터치시 우측 버튼이 '등록중'으로 변경되어 표시 되는건 통신중인 상태를 표시하기 위함인데, 통신되는 동안 계속 버튼이 같은 상태로 표시될 경우 사용자가 전송이 시작된 줄 모르고 추가로 수정 버튼을 눌러 https://github.com/smart-learning/design-2.0/issues/158 의 4번 같은 일이 일어나기 때문입니다.

등록중 이라고 표시되지 않고 등록 이라고만 다시 바꾸어 표시할 수는 있지만 전송이 시작되었음을 알리는 시각적인 처리는 필요할 것으로 생각됩니다.

------

현재 댓글 api 에서 pagination header가 넘어오지 않아 has-next 를 확인할 수 없어 데이터의 끝인 것으로 인식하고 더보기를 출력하지 않고 있는 상태입니다. 확인 부탁드립니다. @jungon-influential

**Comment by welaaa-sangyeon** [comment]
네 확인하였습니다.
의견 감사합니다.

**Comment by shj7831** [comment]
별점/댓글 기능 관련하여
별점 기능: 등록, 수정 가능
리뷰 기능: 등록, 수정, 삭제 가능
-> 기획서를 첨부드리니 아래 기획서의 7,8 페이지를 가이드로 생각하시면 됩니다.

[★ [앱 공통] 별점_ 댓글 기능 기획  .pptx]
(https://github.com/smart-learning/design-2.0/files/2867873/_.pptx)

**Comment by welaaa-sangyeon** [comment]
위에 남겨주신 기획서는 제가 퀵하기 디자인해서 가이드 드리겠습니다

**Comment by jungon-influential** [comment]
pagination header 추가해서 API 배포 했습니다.

**Comment by welaaa-sangyeon** [comment]
![image](https://user-images.githubusercontent.com/44987455/52837403-f3813300-3131-11e9-90e5-23b63a7bd860.png)

- 사양 
  https://xd.adobe.com/spec/e4194aa6-5e6b-4600-4882-d2e1035af278-9228/

별점과 리뷰부분을 제가 잘못드린부분이 있어서 위와같이 수정했으면합니다.
금일 가능하신지 체크좀 부탁드릴게요.
(관련 얼럿 내용은 손희정 대리님께서 덧글로 추가설명 주실겁니다)

**Comment by shj7831** [comment]
리뷰 삭제 버튼 클릭시 알럿창은 아래와 같이 뜨면 됩니다.

<img width="183" alt="default" src="https://user-images.githubusercontent.com/41724109/52837634-df8a0100-3132-11e9-8ad8-1b63b5a47eed.PNG">

**Comment by nanuruya** [comment]
1. 지금 정책상으로 리뷰를 삭제하면 별점은 어떻게 처리되는건가요? 확인 부탁드립니다.
2. 해당 이슈는 UI 변경 및 API 연결 수정이 함께 필요하기때문에 오늘 내에 처리는 어려울것 같습니다.

**Comment by shj7831** [comment]
1. 정책 상으로 아래 기능은 각각 다르게 분리하여 처리합니다.

첫 등록시  
별점 + 리뷰 같이 등록 

수정/삭제할 경우 (별개로 처리)
- 리뷰:  수정, 삭제 가능
- 별점:  수정 가능 (삭제는 불가)
 
따라서, 리뷰 수정/삭제시 별점과는 무관하도록 처리하시면 됩니다.

**Comment by nanuruya** [comment]
네 그럼 api쪽에서 수정되어야 할 것이 있습니다.

`[POST]http://api-prod.welaaa.com/api/v1.0/action/stars/v100020` 성공한 이후에 `[GET]http://api-prod.welaaa.com/api/v1.0/action/stars/v100020` 해보면 

```
{
  "all": {
    "code": "v100020",
    "content_id": 1041,
    "created_at": "2019-01-23T16:09:28+00:00",
    "id": 1000,
    "score": {
      "1": 0,
      "2": 1,
      "3": 0,
      "4": 0,
      "5": 9
    },
    "son_id": 0
  },
  "my": {}
}
```

`my` 항목이 비어있습니다.

별점 수정의 경우 `my` 항목을 기준으로 해야 할 것 같아 확인해주셔야 할 것 같습니다. @jungon-influential

**Comment by jungon-influential** [comment]
POST 후 GET 하면 가져오고 있습니다.

**Comment by Unk** [comment]
swagger-ui 상에서는 확인이 되지 않고, 직접 curl 날려서는 오는 것 확인했습니다.
이 값을 토대로 작업 하겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hoonpapa** [comment]
이슈 확인하여 Closed합니다.
