### ISSUE TITLE
[메인 > 오디오북 > 상세 페이지] 상단 영역 (정보,목차 윗부분) UI 수정

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#124]
오디외북 상세페이지 상단 UI 변경

(App_audio_상세페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51242961-a0964d80-19c4-11e9-85db-817d2ab732fe.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![1](https://user-images.githubusercontent.com/44987455/52047246-f275d080-258b-11e9-87c9-b541f2672154.png)

**Comment by Unk** [comment]
`이와 같은 디자인을 한 적 없음`이라고 언급하신 부분은 저희가 작업한 부분이 아닙니다.
인플루엔셜 개발팀에서 삽입한 내용입니다.
인플루엔셜 저장소의 내용을 병합하면서 옮겨붙은 것으로 보입니다.
리포팅 해주셔서 해당 부분은 삭제 처리 되었습니다.

**Comment by welaaa-sangyeon** [comment]
ㄴ 넵 알겠습니다. 클래스 상세페이지 영역을 잘못 입력했네요;

welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![1](https://user-images.githubusercontent.com/44987455/52054500-193e0200-25a0-11e9-98e2-674c02a02115.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-04-2126-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-04-2126-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549283669050600)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

1. 구매 정책별 노출 내용 재확인 필요
2. 정책별 폰트 사이즈 확인
3. 구매 버튼 반응 없음
4. 이용권 사용시 구매 팝업까진 뜨나 그 이후 진행안됨, 구매 후 해당 오디오북 상세페이지로 가면 아래의 이미지와 같은 오류 발생

![kakaotalk_photo_2019-02-07-17-30-37](https://user-images.githubusercontent.com/44987455/52398982-2efe7a80-2afe-11e9-9c68-a42606c68487.jpeg)

App_audio_상세페이지_구매정책_190116_confirm.xd 참고

**Comment by Unk** [comment]
코드상에 주석은 달아 놓았는데 지금은 앱상에서만 확인하시는 것 같아 코멘트로 따로 말씀 드려야겠네요.

현재 디자인상에서 정리하신 정책 케이스와 실제 API 상에서 내려주는 케이스가 일치하지 않습니다.
일치하는 부분들에 대해서는 작업이 된 상태이고, 일치하지 않는 부분들은 정책만 추가되면 뷰가 구현되도록 작업이 되어 있습니다. (웹으로 비유하면 html, css는 다 짜 놓았고 분기 처리만 추가되면 됩니다)

API 상에서는 `free`, `membership`, `owned`, `rental`, `can_buy` 의 다섯가지 permission type 과 `can_play`라는 다운로드 분기 플래그만 제공하고 있습니다.

디자인 파일 상에서는 오디오의 경우 디바이스별로 5~6가지, 클래스의 경우 최대 10가지 케이스의 정책으로 디자인 하셨는데 이 케이스가 전부 API상에서 구분해서 내려주실 수 있는지 내부에서 확인하시고 저희쪽에 방향을 알려주시면 맞춰서 진행하도록 하겠습니다.

------

구매버튼과 이용권에 대한 부분은 기존에 만들어진 기능들을 연결만 한 부분입니다. 인플루엔셜 개발팀에서 확인 해주셔야 할 것 같습니다.

감사합니다 :)

**Comment by welaaa-sangyeon** [comment]
빠른 확인 감사합니다.
개발팀과 상의하도록 하겠습니다

**Comment by Unk** [comment]
케이스별로 분기하다가 구매 버튼에 이벤트가 할당 안된 경우를 발견했습니다.
터치가 동작한 이후로 나는 에러에 대해서는 서버쪽의 디버깅도 병행되어야 하니 인플루엔셜에서 도와주셔야 할 것 같고, 일단 이벤트가 할당되지 않는 경우가 없게 꼼꼼하게 채워 넣도록 하겠습니다.

**Comment by nanuruya** [comment]
`2. 정책별 폰트 사이즈 확인` 에 대한답변입니다.
현재 구매정첵 레이아웃을 공통요소로 묶어서 작업이 되어있는 상태입니다. 
현재 표시되고 있는 정책중 `별도 구매가 필요합니다` 텍스트가 들어가는 케이스가 있습니다. 이부분을 디자인 대로 표시하면 버튼과 텍스트 간격이 딱 붙어버리는 문제가 있었습니다. 간격 확보를 위해 폰트 사이즈를 임의로 21픽셀로 조정하게 되었습니다. 
해당 문구가 들어가는 케이스가 삭제되거나 문구수정이 된다면 다시 원래 디자인에서 지정한 폰트로 맞춰서 수정 가능합니다.

**Comment by jungon-influential** [comment]
기존에 구현된 로직을 분석하시면 디자인 상에 나와있는 모든 경우가 나올 겁니다.
분석하시는데 도움을 드리자면 디자인 가이드를 보시면 멤버쉽 타입과 오디오북 이용권도 조건에 포함 됩니다.
다 고려해 보시면 모든 조합이 나올 겁니다.

**Comment by Unk** [comment]
기존에 구현된 로직은 분석해서 넣었는데,
기존에는 없던 형태의 디자인이 새로이 추가되는 경우엔 어떻게 넣어야 하죠?
케이스별로 정리를 해서 주셔야 저희가 맞게 작업을 할 수 있지 않을까요..

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![1](https://user-images.githubusercontent.com/44987455/52711202-8b690a80-2fd4-11e9-9d79-3388afde9dad.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
오디오북 상세페이지 + 이달의책 상세페이지 두곳의 플레이 버튼의 opacity 를 수정요청드립니다.

![image](https://user-images.githubusercontent.com/44987455/52849507-8b901400-3154-11e9-9671-71ec5f1060eb.png)
