### ISSUE TITLE
[메인 > 오디오북 > 상세 페이지] 도서 정보 (소개카드,클래스 소개,강사 소개)

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#125]
오디오북 상세페이지 '도서 정보' UI 변경
ㄴ '전체 재생시간', '다운로드시 용량' 아이콘은 전달 예정

(App_audio_상세페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51243057-e4895280-19c4-11e9-8400-0f9ad0e99dc8.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![2](https://user-images.githubusercontent.com/44987455/52054545-4094cf00-25a0-11e9-85c0-3a2db73c00e5.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-04-2126-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-04-2126-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549283669050600)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![2](https://user-images.githubusercontent.com/44987455/52711255-b5bac800-2fd4-11e9-84b8-9380b60f18df.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
