### ISSUE TITLE
[메인 > 오디오북 > 상세 페이지] 목차

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#126]
오디오북 상세페이지 '목차' UI 변경

(App_audio_상세페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51243314-8dd04880-19c5-11e9-938d-1d5a025127e2.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 전체 재생시간 아이콘의 위치가 텍스트와 맞지 않습니다. 조금 하단으로 내려주세요

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![3](https://user-images.githubusercontent.com/44987455/52711313-daaf3b00-2fd4-11e9-967d-b0d19bd7f796.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
