### ISSUE TITLE
[공통] 클래스 리스트, 재생시간, 다운로드 아이콘 적용

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#127]
그동안 비어있던 '재생시간, '다운로드' 아이콘이 제작 완료되었습니다. 
상세페이지, 상세페이지 목차 등, 비어있는 모든 영역에 삽입부탁드립니다.

![image](https://user-images.githubusercontent.com/44987455/51300767-64b8c200-1a70-11e9-8a3d-adc6d5946045.png)

ㄴ 상세페이지에는 각각 40x40 (dp)의 크기로 작업한 예제입니다. (컬러 #353A3C)

거기다 추가로 현재 적용중인 '클래스 리스트' 아이콘 디자인이 변경되어 재공유드립니다.

--
다운로드 - https://drive.google.com/open?id=1vHYkfJ193o61BvexDCly3EsDoTumnR-5

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 적용된 아이콘의 사이즈가 몇 dp인가요? 다소 타이트해보여 여쭤봅니다

**Comment by nanuruya** [comment]
디자인과 동일하게 40dp로 되어있습니다.
