### ISSUE TITLE
API 추가

### ISSUE THREAD

**Issue by jungon-influential** [smart-learning/design-2.0#128]
- [x] 새로 나온 {클래스,오디오북}, 오늘의 인기 {클래스,오디오북} 카테고리에 따라 갱신
> 제안 주신 이름보다 기존에 사용하던 이름으로 유지했습니다.

**클래스**
`http://api-prod.welaaa.com/api/v1.0/cms/main/video/{category}`
http://api-prod.welaaa.com/api/v1.0/cms/main/video 와 동일한 포맷으로 전달됩니다.

**오디오북**
`http://api-prod.welaaa.com/api/v1.0/cms/main/audiobook/{category}`
http://api-prod.welaaa.com/api/v1.0/cms/main/audiobook 과 동일한 포맷으로 전달됩니다.

```
{
	"hot": [],
        "new": [],
        "recommend": []
}
```

- [x] 평가 및 리뷰
> swagger 참조

**조회**
`GET http://api-prod.welaaa.com/api/v1.0/action/stars/{content_code}`
> 비회원이거나 자신이 작성한 댓글이 없을 경우 my 필드에는 값이 빈 값으로 출력됨
```
{
  "all": {
    "code": "v200010",
    "content_id": 128,
    "created_at": "2019-01-23 16:09:28",
    "id": 1017,
    "score": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 3,
      "5": 5
    },
    "son_id": 0
  },
  "my": {}
}
```
**별점 등록 (회원인증필수)**
`POST http://api-prod.welaaa.com/api/v1.0/action/stars/{content_code}`
```
body
{ "content": "integer" }
```

**별점 삭제 (회원인증필수)**
`DELETE http://api-prod.welaaa.com/api/v1.0/action/stars/{star_id}`

**별점 수정 (회원인증필수)**
`PATCH http://api-prod.welaaa.com/api/v1.0/action/stars/{star_id}`
```
body
{ "content": "integer" }
```

- [x] 이달의 책 배경, 멘토

**배경 색상 추가**
```
[
	"...",
	{
		"bg_color": "#ededed",
		"book_a": {
			"..."
                        "mentor":""
		},
		"book_b": {
			"..."
                        "mentor":""
		},
		"month": "2018-12-01"
	},
	"..."
]
```

**Comment by hyunggoo-kang** [comment]
@jungon-influential   완료된 이슈면 close해주세요.

**Comment by jungon-influential** [comment]
API 정상동작 확인 및 전달했습니다. 이슈 닫겠습니다.
