### ISSUE TITLE
[목록 공통] 카테고리 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#13]
- [x] `All` 추가
- [x] 선택메뉴 컬러 표기
- [x] 스와이핑 영역임을 알 수 있도록 텍스트 걸쳐있기
- [ ] sticky 처리

![image](https://user-images.githubusercontent.com/3823119/48415139-e8fc7980-e78f-11e8-94a1-01f5aaf06cf9.png)

**Comment by welaaa-sangyeon** [comment]
클래스도 아래와 같은 형식으로 작업부탁드립니다.

(App_audio_전체리스트_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51242428-4ea0f800-19c3-11e9-847a-d27e5745438d.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![default](https://user-images.githubusercontent.com/44987455/52710561-f9accd80-2fd2-11e9-9f04-05ac0490f686.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
