### ISSUE TITLE
[메인 > 클래스 전체 리스트] 디자인 변경

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#131]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52047895-5cdb4080-258d-11e9-8d03-b768f7aa5459.png)

**Comment by nanuruya** [comment]
콤포넌트 노출 정책 미적용에 대한 답변입니다.
`<FlatList>` 태그에서 지원하는 `onEndReached` 이벤트로 처리 해놓아서 해당 노출 정책이 동작되는 상태였습니다. `onEndReached` 이벤트에 `fallback` 플랜이 없어서 추가 로드가 안되는 문제가 있었습니다. 
현재 `<ScrollView>` 태그에  `onScroll`  이벤트로 대체하여 해결하였고, 다음 apk 전달시 반영됩니다.

**Comment by nanuruya** [comment]
컴포넌트 노출정책 수정한 내용먼저 
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.
나머지 수정사항은 다음 빌드 버전에 적용됩니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

노출 정책(20개 노출, 스크롤시 추가로 20개)이 명확하게 적용되지 않은 것 같습니다.
카테고리 다른것 같기도 한데, 확인 한번 부탁드립니다.
