### ISSUE TITLE
[메인 > 오디오북 > 상세페이지] 도서 정보 (평가, 리뷰 남기기)

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#132]
welaaa-1.50.050-2019-01-31-0901-design-release.apk

--
![3](https://user-images.githubusercontent.com/44987455/52054639-86ea2e00-25a0-11e9-9bbb-6388acfaed9e.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-04-2126-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-04-2126-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549283669050600)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

덧글 입력 안됨
(그 외 확인 완료)

**Comment by Unk** [comment]
덧글 입력시 무응답인가요? 에러 내용이 오나요? 에러 코드가 있나요? 코드가 없이 에러에 대한 단순 안내만 나오나요? 자세한 상황을 알려주시면 좋겠습니다.

**Comment by welaaa-sangyeon** [comment]
텍스트 입력창 터치 시 키보드는 뜨는데 어떤 내용도 입력되지 않습니다.

**Comment by Unk** [comment]
전송이 아니라 아예 입력에서부터 안되는 거네요.
이미 예시로 올라간 리뷰도 여럿 있어서 입력이 안되는 기기가 있을줄은...
기기 정보 좀 알려주시겠어요?
운영체제 버전이랑요.

**Comment by welaaa-sangyeon** [comment]
저희가 가지고 있는 모든 기종에서 안되는것 같은데 다 말씀드려야 하나요?

**Comment by Unk** [comment]
그럼 대표 기종 몇개만 말씀해주세요.
저희쪽에서 재현되지 않으니 저희가 뭔가 기준을 잡고 해당 기기에서 재현을 시도해봐야 하니까요.

**Comment by Unk** [comment]
일단 저희쪽 기기 중에 V20에서 재현되는 조건을 찾았으니 V20에서 먼저 테스트 해보고 있겠습니다.

**Comment by welaaa-sangyeon** [comment]
LG G7 - aOS 8.0.0
갤럭시 S6 - aOS 7.0
갤럭시 s9 - aOS 8.0.0

**Comment by Unk** [comment]
`welaaa-1.50.050-2019-02-08-0915-design-release.apk`  
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549585112015800

**Comment by welaaa-sangyeon** [comment]
클래스와 마찬가지로 '**오디오북** 내용은 어떠셨나요?' 오디오북 내용을 추가 부탁드립니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-11-1726-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-11-1726-design-release.apk  
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549874072008300)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

#123 과 같은 이슈입니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by nanuruya** [comment]
이전 버전에 반영된 내용입니다. 확인 후 추가 이슈가 없다면 클로즈 부탁드립니다.
