### ISSUE TITLE
[공통] 앱 뱃지 적용

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#137]
App_badge_190208.xd 참고

클래스, 오디오북 컴포넌트에 사용되는 뱃지가 정리되어 공유드립니다.

![image](https://user-images.githubusercontent.com/44987455/52458752-9f5fd700-2ba4-11e9-8c6b-57e0b32fdc1a.png)

**Comment by Unk** [comment]
디자인 확정 이후로 너무 자주 변경되는 것 같습니다.
여러가지 이유로 검수 일정이 미루어지는 와중에 계속 변경사항이 생기는 부분은 서로간에 오해의 여지가 있으니 조금 신경써 주시면 좋겠습니다.

------

각각의 뱃지가 API상에서 어떤 플래그를 이용해서 표시해야 하는지 정리를 한번 해주시면 좋겠습니다.
BEST 항목에 대한 플래그가 기존 플래그 중에서는 존재하지 않고요,
북리뷰 뱃지 같은 경우 API상의 값만으로 보면 추정할 수 있는 필드가 2개(audiobook_type = '북리뷰', is_bookreview)가 있어 어느 값을 기준으로 분기해야 할지 이름만으로는 명확하지 않는 등의 문제가 있습니다.

@jungon-influential

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 구현해주신 뱃지디자인이 오디오북 리스트에서만 다른 사이즈로 보이는데 확인 부탁드립니다.
(맨 위 이미지처럼 같은 크기를 가집니다)

**Comment by Unk** [comment]
무료, 추천, 완독, 요약, 북리뷰 가 같은 사이즈이고
오리지널, NEW, BEST 가 같은 사이즈로 보이는데요.
분리할 수 있는 기준이 현재 API상엔 존재하지 않아서 차이를 두기 힘들 것 같습니다.

1. 어떤 텍스트가 오든 다 같은 사이즈로 표시한다 (근데 그럼 https://github.com/smart-learning/design-2.0/issues/137#issue-408000981 의 이미지처럼 한줄에 5개가 표시할 수는 없습니다)
2. 사이즈를 API에서 지정해준다

중 하나로 해결해야 할 것 같습니다.

**Comment by Unk** [comment]
혹시 width가 아니고 height에 대한 코멘트를 주신건가요?

**Comment by welaaa-sangyeon** [comment]
오리지널을 제외한 나머지 뱃지는 width값이 같습니다..

좀전에 수정된 api를 보내주셨다고 하니 확인해보겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
