### ISSUE TITLE
[02/08][Android][오디오북] 콘텐츠 정보 내 도서정보 탭의 이미지와 맞게 아이콘이 롤링되지 않는 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#138]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/08) / 윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0208@qa.com / 1

[상세 내용]
오디오북 콘텐츠 중 "어디서 살 것인가"의 도서정보 부분의 이미지와 롤링 아이콘이 상이합니다.

[이슈 경로]
1. 로그인
2. 이달의 책 오디오북 중 "어디서 살 것인가" 클릭
3. 책 상세보기 클릭
4. 도서정보의 이미지 롤링 후 확인
![020803](https://user-images.githubusercontent.com/45928019/52459209-257d1d00-2ba7-11e9-9a8e-a5e91bff1a63.png)

**Comment by Unk** [comment]
## 원인

`react-native-swiper`에서 스와이프 변경에 대한 이벤트가 딜레이 호출 되고 있습니다.

| 슬라이드 1 | 슬라이드 2 | 슬라이드 3 | 슬라이드 4 | 슬라이드 5 |
|---|---|---|---|---|
| 이벤트 발생 | 이벤트 발생 | (무반응) | (무반응) | 이벤트 발생<br>이벤트 발생<br>이벤트 발생 |

이런식으로 이벤트가 몰려서 발생하며, 몰려서 발생하는 시점에 인디케이터가 업데이트 되는 게 확인됩니다.

## 대안

추천시리즈나 이달의 책에 적용된 `react-native-snap-carousel`으로 대체할 수 있을 것 같습니다.
다만 인디케이터 부분에 대한 디자인 작업이 필요하기 때문에 이 부분은 시간을 좀 할당해야 하는 작업입니다.

**Comment by hyunggoo-kang** [comment]
@Unk 메인 배너쪽 스와이프와 유사해보이는데 이 디자인으로 바로 적용이 될수 있지 않을까요?

**Comment by Unk** [comment]
같은 스와이퍼이나 상세에서만 문제가 발생하고 있습니다.

**Comment by hyunggoo-kang** [comment]
이 이슈와 관련이 있는지는 모르겠지만 현재 오디오북 상세 페이지의 UI 반응 속도가 상당히 느립니다. 클릭후 몇초가 지나야 반응이 오는데 이 부분이 같이 개선이 되어야 할것 같습니다.

**Comment by Unk** [comment]
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549965106048700 와 같은 일이 있었는데 혹시 비슷한 상황일까요?

**Comment by hyunggoo-kang** [comment]
현재 보고 있는것은 release빌드라서 관련은 없을것 같습니다.  위의 이슈를 해결한뒤에도 여전히 느린지 확인이 필요할것 같습니다.

**Comment by Unk** [comment]
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550225779131100?thread_ts=1550225655.130600&cid=GE1C2BEG5 부분과 관련이 있는 부분으로, `onEndReached` 삭제시에 스와이퍼도 성능이 개선되는 것을 확인할 수 있었습니다.

**Comment by hyunggoo-kang** [comment]
성능 개선후 해당 이슈도 재현되지 않음 close처리함.
