### ISSUE TITLE
[02/08][Android][오디오북] 매일 책 한권의 포스터가 출력되지 않는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#139]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/08) / 윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0208@qa.com / 1

[상세 내용]
오디오북 탭의 매일 책 한권의 포스터 부분이 출력되지 않습니다.

[이슈 경로]
1. 로그인
2. 오디오북 탭 클릭
3. 금일의 매일 책 한권 포스터 확인
![020804](https://user-images.githubusercontent.com/45928019/52459494-d33cfb80-2ba8-11e9-898c-aeba3b043b54.png)

**Comment by Unk** [comment]
서버에서 회색 이미지를 보내오고 있습니다.

**Comment by leejonghun92** [comment]
해당 이미지에 재생 아이콘도 추가되어야할 것 같습니다.

**Comment by nanuruya** [comment]
@leejonghun92 재생 아이콘은 디자인상 원래 없는 요소입니다.

![image](https://user-images.githubusercontent.com/3823119/52766534-ca499f80-306a-11e9-89d5-a1a13afc3368.png)

**Comment by leejonghun92** [comment]
해당 이슈 재현 되지 않았습니다. 검증 완료 하였습니다.
