### ISSUE TITLE
[02/13][Android][클래스] 무료 클래스 다운로드 완료 후 다운로드 버튼이 그대로인 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#141]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/13)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021301@qa.com / 1

[상세 내용]
무료 클래스 다운로드 완료 후 다운로드 버튼이 그대로 남아있습니다.
(*뒤로가기 후 다시 돌아오면 변경되어 있음)

[이슈 경로]
1. 로그인
2. 임의의 무료 클래스 다운로드
3. 다운로드 완료 확인
4. 다운로드 버튼 그대로 남아있음
![021301](https://user-images.githubusercontent.com/45928019/52681509-67c7a500-2f7f-11e9-83ec-09346b17e692.png)

**Comment by leejonghun92** [comment]
무료 오디오북/클래스 다운로드 완료가 되면 앱 강제종료 됩니다.

**Comment by jungon-influential** [comment]
W10-291 이슈 수정으로 해결완료

**Comment by leejonghun92** [comment]
해당 이슈 수정 되었습니다. 검증 완료 하였습니다.
