### ISSUE TITLE
[02/13][Android][평가/리뷰] 평점과 리뷰를 남길 때 평점이 반영 안되는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#142]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/13)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021301@qa.com / 1

[상세 내용]
리뷰는 등록되지만 평점은 평가에 반영되지 않습니다.

[이슈 경로]
1. 로그인
2. 임의의 클래스 클릭
3. 평점과 리뷰를 등록
4. 등록된 것을 확인
![021302](https://user-images.githubusercontent.com/45928019/52682024-613a2d00-2f81-11e9-9b35-5b4166d824bb.png)

**Comment by hoonpapa** [comment]
IOS도 동일현상 발생하고있습니다.

**Comment by leejonghun92** [comment]
별점 또한 반영되지 않습니다.
![0214](https://user-images.githubusercontent.com/45928019/52765614-f6afec80-3067-11e9-9421-52ba07b66f24.png)

**Comment by hyunggoo-kang** [comment]
플레이어쪽은 원래 동작하지 않았던 것으로 알고 있습니다. @jungon-influential  플레이어쪽도 수정 가능할까요?

**Comment by jungon-influential** [comment]
네 수정하겠습니다.

**Comment by leejonghun92** [comment]
해당 이슈 검증 완료 하였습니다. 플레이어 쪽 별점이슈는 Jira에 새로 등록하도록 하겠습니다.
