### ISSUE TITLE
[02/13][IOS][클래스]윌라 클래스 추천시리즈 및 오디오북 이달의책 롤링시 터치 무감현상 및 롤링되지 않은 이슈 발생

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#145]
[Test 환경]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 윌라 클래스 추천시리즈 및 오디오북 이달의책 롤링 동작
3. 터치 무감 및 롤링 되지 않음(처음에는 정상동작하나 계속 롤링시 동작 되지 않음)
4. 이달의책 자세히 보기 버튼X
5. 이달의책 터치해도 아무 동작 하지 않음

**Comment by leejonghun92** [comment]
[AOS]도 동일한 이슈 발생합니다.

**Comment by hoonpapa** [comment]
Issue 개선 확인하여 Closed합니다.
