### ISSUE TITLE
[02/13][Android][이달의책] 콘텐츠 포스터의 재생아이콘 클릭 시 반응이 없는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#146]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/13)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021301@qa.com / 1

[상세 내용]
이달의 책 탭의 포스터에서 재생아이콘 클릭 시 아무 반응이 없습니다.

[이슈 경로]
1. 로그인
2. 오디오북 메뉴 탭
3. 이달의 책 중 임의로 클릭
4. 포스터의 재생아이콘 클릭
![021305](https://user-images.githubusercontent.com/45928019/52687186-27265680-2f94-11e9-9c8c-387860fa065d.png)

**Comment by hoonpapa** [comment]
IOS도 동일현상 발생하고있습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by leejonghun92** [comment]
해당 이슈 수정되어 재현되지 않습니다. 검증 완료 하였습니다.
