### ISSUE TITLE
[02/13][Android][매일책한권] 매일 책 한권 보러가기 버튼과 오디오북 전체보기 버튼 클릭 시 동일한 화면이 나타나는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#147]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/13)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021301@qa.com / 1

[상세 내용]
오디오북 탭의 매일 책 한권 보러가기 버튼을 클릭했을 때와 오디오북 전체보기 버튼을 클릭했을 때 동일한 화면이 나타납니다.

[이슈 경로]
1. 로그인
2. 오디오북 메뉴 탭
3. 매일 책 한권 보러가기 버튼 클릭
4. 오디오북 전체보기 버튼 클릭 후 화면 비교
![021306](https://user-images.githubusercontent.com/45928019/52688076-08c25a00-2f98-11e9-92d1-033ce0db0fc5.png)

**Comment by leejonghun92** [comment]
재확인결과 오디오북 전체보기 버튼을 클릭했을 때 전체가 아닌 북리뷰 탭 내의 화면으로 나타납니다.

**Comment by hyunggoo-kang** [comment]
@shj7831  기대되는 동작이 뭔가요?

**Comment by shj7831** [comment]
@hyunggoo-kang  @leejonghun92  
[매일 책 한권 보러가기]  클릭시 
-> 오디오북 전체목록 화면의 [북리뷰] 카테고리- [업데이트 순]으로 Focus 되어서 랜딩되면 된다고 합니다.

**Comment by shj7831** [comment]
@leejonghun92  
지금 오디오북 메인 화면 하단에서 [오디오북 전체보기] 클릭시 오디오북 전체 목록에서 [전체] 로 focusing 되어야 하니 확인 후 이슈 등재 부탁드립니다.

**Comment by leejonghun92** [comment]
@shj7831 
네 새로 이슈 등재하도록 하겠습니다.

**Comment by nanuruya** [comment]
https://github.com/smart-learning/design-2.0/issues/34#issuecomment-463894556
와 동일한 이슈입니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by leejonghun92** [comment]
해당 이슈 검증 완료 하였습니다.
