### ISSUE TITLE
[02/13][Android][클래스] 해당 콘텐츠 재생되지 않는 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#148]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.050(02/13)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021301@qa.com / 1

[상세 내용]
윌라 프리미엄 클래스 중 "수포자인 저도 수학이 필요한 순간이 있을까요?" 콘텐츠가 재생되지 않습니다.

[이슈 경로]
1. 로그인
2. 윌라 프리미엄 클래스
3. 새로나온 클래스
4. "수포자인 저도 수학이 필요한 순간이 있을까요?" 재생시도
![021307](https://user-images.githubusercontent.com/45928019/52688460-f21d0280-2f99-11e9-9547-f2dfb2082aa6.png)

**Comment by Unk** [comment]
모든 영상에서 같은 이슈가 발생하는 것이 아니고 이 컨텐츠에서만 발생하는 현상인가요?

**Comment by leejonghun92** [comment]
> 모든 영상에서 같은 이슈가 발생하는 것이 아니고 이 컨텐츠에서만 발생하는 현상인가요?

네 해당 콘텐츠에서만 이슈 발생합니다.

**Comment by hyunggoo-kang** [comment]
@leejonghun92  다른 기기에서의 테스트 결과는 어떤가요?

**Comment by jungon-influential** [comment]
발생한 테스트 기기에서 지금은 재생이 됩니다.
일시적인 문제인지 크래쉬 리포트 확인 하도록 하겠습니다.

**Comment by leejonghun92** [comment]
해당 이슈 재현되지 않습니다. 검증 완료 하였습니다.
