### ISSUE TITLE
[02/13][IOS][오디오북]오디오북 단품구매후 소장중임에도 구매버튼 선택시 구매하시겠습니까 팝업 출력

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#150]
[Test 환경]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Dev

1. 윌라 계정 로그인
2. 오디오북 임의의책 선택
3. 구매 
3. 구매완료후 다시 구매버튼선택시 소장중임에도 구매하시겠습니까 팝업 출력

![img_0030](https://user-images.githubusercontent.com/45807513/52690968-b9355b80-2fa2-11e9-825a-c8f70aeb640f.PNG)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by hoonpapa** [comment]
구매한 오디오북 화면으로 진입시 
![cb9def57-d716-4ea4-98bb-f57f5422152d](https://user-images.githubusercontent.com/45807513/52828723-4399ce80-310d-11e9-81cc-e8e9f4711339.png)
화면 출력하며 이후 동작 할수없습니다.
확인 부탁드립니다.

**Comment by hoonpapa** [comment]
iphone에 소장중이라는 문구와 다운로드/구매 버튼이 보이지 않습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hoonpapa** [comment]
#172 이슈 확인 부탁드립니다.
구매버튼이 노출하지 않아 이슈 새로 등재하였습니다. 
다운로드/구매 버튼이 보이지 않습니다.

**Comment by Unk** [comment]
본 이슈는 버튼 노출에 대한 이슈와는 다른 호출시 오류에 대한 내용이므로 close 요청드립니다.
노출에 대한 이슈는 #172 에서 처리되면 될 것 같습니다.

**Comment by hoonpapa** [comment]
#172 개선 확인후 이슈 재발생시 Reopen하도록 하겠습니다.
