### ISSUE TITLE
[02/13][IOS][클래스]클래스 멥버십, 프리미엄 멤버십 가입후 클래식 상세화면 진입시 다운로드 선택부분이 없음(디자인 이전버전에는 다운로드 버튼이 있음)

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#151]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Device : iPhone6s+

1. 윌라 계정 로그인(클래스 멥버십, 프리미엄 멤버십 가입되어있는 계정)
2. 임의의 클래스 선택
3. 클래스 다운로드 버튼 유무 확인

![123](https://user-images.githubusercontent.com/45807513/52691920-af612780-2fa5-11e9-9210-46490c31b80a.png)

**Comment by nanuruya** [comment]
IOS 구매정책 관련 참고 
https://github.com/smart-learning/design-2.0/issues/165

**Comment by nanuruya** [comment]
이전 버전에 반영된 내용입니다.

**Comment by hoonpapa** [comment]
다운로드 버튼이 보이지 않습니다. 확인 부탁드립니다.

**Comment by hyunggoo-kang** [comment]
AOS에서는 잘 노출되고 있는데 IOS에서만 이슈 발생합니다. 저 영역이 아예 안나오네요.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1858-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1858-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550570507168400)

**Comment by hoonpapa** [comment]
![bc4a2246-c09e-4a43-85a4-ff11cc3be3e2](https://user-images.githubusercontent.com/45807513/53059138-3b6cd500-34f9-11e9-8265-8c1dae249e5e.png)
무제한 이용가능 문구는 생성되었으나 다운로드 버튼은 없습니다. 확인 부탁드립니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1306-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1306-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550635979176500)
