### ISSUE TITLE
[02/13][IOS][클래스]리뷰 남기기 선택시 키보드 올라오며 글씨쓰는 부분이 키보드에 가려지는 현상 발생

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#152]
[Test 환경]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스 선택
3. 리뷰 남기기 선택 
4. 키보드 올라오며 리뷰 남기는칸이 안보이는 현상 발생

![234](https://user-images.githubusercontent.com/45807513/52693154-49769f00-2fa9-11e9-818b-c23fca0a2130.png)

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hoonpapa** [comment]
issue 개선 확인하여 Closed합니다.
