### ISSUE TITLE
[02/14][IOS][오디오북]오디오북 이달의책 보유권이 이전 버전에서는 보이나 현버전에서는 보이지 않음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#153]
[Test 환경]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Device : iPhone6s+

1. 윌라 계정 로그인(프리미엄 멤버십 가입되어있는 계정)
2. 오디오북 이달의책 확인
3. 보유권이 이전 버전에서는 보였는데 현버전에서는 보이지 않음
![123](https://user-images.githubusercontent.com/45807513/52756706-a1fb7a00-3045-11e9-86af-2f10298cd64f.png)

**Comment by jungon-influential** [comment]
현재 보유권 표시는 하지 않는 것으로 확인했습니다.

**Comment by welaaa-sangyeon** [comment]
해당 이슈는 정책상 표기 되지 않는 것으로 결정되어 닫도록 하겠습니다.
