### ISSUE TITLE
[02/14][IOS][클래스/오디오북]홈화면에서 아래로 스크롤시 클래스/오디오북 탭이 사라지는 현상 발생

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#154]
[Test 환경]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 클래스/오디오북 화면에서 아래로 스크롤
3. 클래스/오디오북 탭이 사라지는 현상 발생(이전버전에서는 탭 유지)
![1234](https://user-images.githubusercontent.com/45807513/52756985-89d82a80-3046-11e9-9344-d0c247da4834.png)

**Comment by welaaa-sangyeon** [comment]
해당 이슈는 디자인과 정책이 정해진 부분이라 닫도록 하겠습니다
