### ISSUE TITLE
[02/14][IOS][오디오북]오디오북 이달의책 그림자 부분이 안드로이드와 반대로 설정되어있음/ 클래스오늘의 추천시리즈도 그림자 부분이 반대로 설정되어있습니다.

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#155]
[Test 환경]
Welaaa App ver: Welaaa 1.5.7(1521qa190212)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 오디오북 이달의책 확인
3. 이달의책 그림자 부분이 안드로이드와 반대로 설정되어있음
![12345](https://user-images.githubusercontent.com/45807513/52758407-79767e80-304b-11e9-9eee-e641358ef7bf.png)

**Comment by hoonpapa** [comment]
![7df17f9e-cfa7-45bc-bcd7-78c8e7921108](https://user-images.githubusercontent.com/45807513/52985759-8ffc4b80-3438-11e9-8f8f-75e5edc23239.png)
클래스 윌라 추천 시리즈도 동일하게 안드로이드와 반대로 설정 되어있습니다.

**Comment by Unk** [comment]
[react-native-snap-carousel](https://github.com/archriss/react-native-snap-carousel)의 기본 스펙이 ios와 안드로이드가 서로 다른 방향으로 stack carousel 되도록 되어 있는데,

방향에 대한 옵션은 제공하질 않아서 같은 방향으로 맞추기는 어려울 것 같습니다.

![ios](https://camo.githubusercontent.com/9b4f2656a078c98e61e3e4ea26730f82701cd02d/68747470733a2f2f692e696d6775722e636f6d2f633770553472542e676966)
![android](https://camo.githubusercontent.com/b6b848a966da059b0a6c50664d838b1d675a3183/68747470733a2f2f692e696d6775722e636f6d2f416e72756163522e676966)

**Comment by hyunggoo-kang** [comment]
@welaaa-sangyeon  피드백 주세요~

**Comment by welaaa-heejae** [comment]
디자인팀 의견은 각 OS 별로 스와이프 방향이 바뀌는 것은 크게 문제될 것 같지 않습니다. 참고해주세요.

**Comment by hyunggoo-kang** [comment]
그럼 close 하겠습니다.
