### ISSUE TITLE
[02/15][Android][오디오북] 오디오북 탭의 오디오북 전체보기 클릭 시 북리뷰 화면이 나타나는 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#157]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.049(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
오디오북 탭의 오디오북 전체보기 버튼 클릭 시 북리뷰 화면이 나타나게 됩니다.

[이슈 경로]
1. 로그인
2. 오디오북 탭 클릭
3. 오디오북 전체보기 버튼 또는 전체보기 버튼 클릭
4. 북리뷰 화면 확인
![021506](https://user-images.githubusercontent.com/45928019/52831024-56fd6780-3116-11e9-809e-4937b175fea1.png)

**Comment by Unk** [comment]
`매일 책 한권 보러가기`에 수정한 부분에서 사이드 이펙트가 발생한 것 같습니다.
확인해보도록 하겠습니다.

**Comment by leejonghun92** [comment]
해당 이슈 검증 완료 하였습니다. 재현되지 않습니다.
