### ISSUE TITLE
[02/15][IOS][리뷰]디자인 리뷰 버전 기획서와 상이한 동작 정리

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#158]
[Test 환경]
Welaaa App ver: Welaaa 1.5.8(1522qa190215)
Device : iPhone6s+

1. 댓글남기기 초기에 적혀있는 글씨 정리 되어있지 않음
2. 리뷰작성후 새로운 리뷰 작성할수없음
3. 댓극 수정확인시 수정/삭제 같이 나와야되는데 수정만 나오고 삭제부분 나오지 않음
4, 리뷰 등재 버튼 연속 선택시 동일한 리뷰가 여러 번 등재됨
![1](https://user-images.githubusercontent.com/45807513/52831013-4e0c9600-3116-11e9-9d7a-7f44d82186d8.png)
![2](https://user-images.githubusercontent.com/45807513/52831014-4e0c9600-3116-11e9-8ba9-944a49b6f7ac.png)
![3](https://user-images.githubusercontent.com/45807513/52831015-4ea52c80-3116-11e9-95db-7a730284caa6.png)
![4](https://user-images.githubusercontent.com/45807513/52831016-4ea52c80-3116-11e9-8ca9-4c3afdea18d0.png)

**Comment by Unk** [comment]
0. **저희는 이 기획서를 전달 받은 적이 없습니다.**
1. `댓글 남기기 초기에 적혀있는 글씨` 라는게 place holder 같은 것을 말씀하시는 건가요? 해당 내용에 대한 디자인이나 가이드를 받은 적이 없습니다.
2. 리뷰는 작성한 적이 있으면 수정만 가능하고 추가로 작성할 수 없는 기획이라고 전달 받았습니다.
3. 저희가 가이드로 삼은 디자인에는 수정만 가능하도록 되어 있었습니다.
4. 이 부분은 저희가 확인해보겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hoonpapa** [comment]
리뷰 동작 확인하여 Closed합니다.
리뷰에대한 새로운이슈 발생시 신규 Issue로 등재 하도록 하겠습니다.
