### ISSUE TITLE
[02/15][Android][오디오북] 무료 오디오북 다운로드 시 앱 강제종료 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#159]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.049(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
오디오북 탭의 무료 오디오북 다운로드 시 앱 강제종료 되어집니다.

[이슈 경로]
1. 로그인
2. 오디오북 탭 클릭
3. 무료 오디오북 클릭
4. 다운로드 버튼 클릭 후 확인
![021505](https://user-images.githubusercontent.com/45928019/52831095-acd20f80-3116-11e9-8056-d64ef02fa242.png)

**Comment by Unk** [comment]
FC 발생시 JS단에서는 아무 로그가 없습니다.
네이티브단 다운로드 컴포넌트쪽 로그나 크래쉬 리포트에서 확인이 가능하신지 요청 드립니다.

**Comment by jungon-influential** [comment]
W10-291 이슈 수정으로 해결완료

**Comment by leejonghun92** [comment]
해당 이슈 검증 완료 하였습니다. 재현되지 않습니다.
