### ISSUE TITLE
[02/15][Android][추천시리즈] 윌라 홈 화면의 윌라 추천시리즈 포스터에 테스트 문구가 남아있는 현상 발생  

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#160]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.049(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
윌라 홈 화면 내 윌라 추천시리즈 포스터에 테스트 문구가 남아있습니다.

[이슈 경로]
1. 로그인
2. 홈 화면의 추천시리즈 확인
3. 테스트 문구 확인
![021504](https://user-images.githubusercontent.com/45928019/52831198-19e5a500-3117-11e9-8acf-bedc5a448a58.png)

**Comment by Unk** [comment]
API 상에서 title 값을 조정해주시면 됩니다.

**Comment by leejonghun92** [comment]
해당 이슈 검증 완료 하였습니다. 재현되지 않습니다.
