### ISSUE TITLE
[02/15][Android][리뷰] 평가되어있는 콘텐츠에 리뷰를 등록할 때 평가된 기록이 사라지는 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#161]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.049(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
평가되어있는 콘텐츠에 리뷰를 등록하면 평가되었던 기록들이 사라지게 됩니다.

[이슈 경로]
1. 로그인
2. 평가되어있는 콘텐츠 클릭
3. 리뷰 남기기
4. 평가되어있던 기록이 사라짐
![021503](https://user-images.githubusercontent.com/45928019/52831260-574a3280-3117-11e9-8bba-88eab6569d52.png)

**Comment by Unk** [comment]
댓글 등록시 해당 데이터도 다시 로드를 해오고 있는데 그 과정에서 문제가 있는지 확인해보겠습니다

**Comment by Unk** [comment]
현재 재현경로 찾는 중입니다.
오디오북 대부분이 별점 0개인 항목들이라서 별점이 어느정도 들어간 항목에 테스트를 해야 할 것 같은데, 첨부하신 이미지는 어느 컨텐츠에서 테스트를 하신건지 알 수 있을까요?

**Comment by leejonghun92** [comment]
> 현재 재현경로 찾는 중입니다.
> 오디오북 대부분이 별점 0개인 항목들이라서 별점이 어느정도 들어간 항목에 테스트를 해야 할 것 같은데, 첨부하신 이미지는 어느 컨텐츠에서 테스트를 하신건지 알 수 있을까요?

클래스에서도 확인 가능합니다~ Ex) "브랜드 스타로 만들어 주는 상상엔진, Self Branding" 클래스 콘텐츠

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by leejonghun92** [comment]
해당 이슈 재현되지 않습니다. 검증 완료 하였습니다.
