### ISSUE TITLE
[02/15][Android][평점] 평가된 평점이 그래프와 상이한 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#162]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.049(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
평가되어있는 평점이 평점그래프와 상이합니다.

[이슈 경로]
1. 로그인
2. "루이비통 스토리, 사치가 아닌 가치를 담아라" 콘텐츠 클릭
3. 평점과 평점그래프 확인
![021502](https://user-images.githubusercontent.com/45928019/52831322-8f517580-3117-11e9-897b-b6f3cc8014f4.png)

**Comment by Unk** [comment]
API에서 보내주는 값과 비교대조 해보도록 하겠습니다.

**Comment by Unk** [comment]
https://api-prod.welaaa.com/api/v1.0/contents/video-courses/209 에서
```
{
   ...
   "star_avg":4.3,
}
```
로 응답을 보내주고 있고
https://api-prod.welaaa.com/api/v1.0/action/stars/v200087 에서
```
{
   "all":{
      "code":"v200087",
      "content_id":209,
      "created_at":"2019-01-23T16:09:29+00:00",
      "id":1093,
      "score":{
         "1":0,
         "2":0,
         "3":1,
         "4":0,
         "5":0
      },
      "son_id":0
   },
   "my":{

   }
}
```
로 응답을 보내주고 있습니다.

API에서만 업데이트가 되면 앱에서도 정상 표시 될 것으로 보입니다.

**Comment by hyunggoo-kang** [comment]
@hanvic  요 이슈좀 봐주세요.

**Comment by hanvic** [comment]
확인하겠습니다.

**Comment by Unk** [comment]
추가로 별점 POST 한 후 GET 해올 때

```
{
   "all":{
      ...
      "score":{
         "1":0,
         "2":0,
         "3":0,
         "4":0,
         "5":0
      },
      ...
   },
   "my":{
      ...
      "id": ...
      ...
   }
}
```

위와 같이 `my`에 데이터가 1건이 있음에도 `all`에서 `score`가 모두 0건으로 데이터가 와서 화면에는 여전히 모든 별점이 0으로 표시되고 있습니다. 이 부분도 같이 봐주시면 좋겠습니다.

**Comment by leejonghun92** [comment]
현재 해당 이슈 재현되고 있습니다.

**Comment by hyunggoo-kang** [comment]
전체 별점 부분이 아래 부분과 상이함.

**Comment by hyunggoo-kang** [comment]
@nanuruya  API 상에서는 
{
  "all": {
    "code": "v200045",
    "content_id": 163,
    "created_at": "2019-01-23T16:09:28+00:00",
    "id": 1052,
    "score": {
      "1": 1,
      "2": 0,
      "3": 2,
      "4": 4,
      "5": 5
    },
    "son_id": 0
  },
  "my": {}
}

로 리턴되고 있어서 전체 별점의 경우 직접 계산을 하셔서 사용하실것 같은데요 위의 데이터의 경우는 평균값이 4이지만 별 모양으로 표시되는 전체 별점은 4.5 정도로 표시가 되고 있어서 확인이 필요합니다.

**Comment by nanuruya** [comment]
평점은 앱단에서 계산하지 않고 서버에서 계산해 보내주는 값을 사용합니다.

평점을 보내주는 API가 2군데로 나뉘어 있어 코드에 양쪽에 혼재된 문제가 있었습니다.
`/contents/video-courses/{id}` 에서는 `3.8`
`/action/stars/{cid}` 에서는 `4.1412`
로 각기 다른 값을 보내오고 있었습니다.

전자의 케이스가 맞는 것으로 보여 앱 전반에서는 전자의 평점만 사용하도록 업데이트 했습니다.

그리고 numeral 라이브러리를 통한 평점 포맷팅이 `0a`로 지정되어 `0.0`로 변경하는 내용도 이번 커밋에 포함되었습니다.

**Comment by hanvic** [comment]
video-courses에 있는 데이터 말고 stars에 있는 데이터를 사용하시면 되겠습니다.

**Comment by hanvic** [comment]
별점 부분을 contents와 테이블을 같이 사용하던것에서 분리하는 과정에 있어서 서로 상이한 부분이 있는데
결론적으로는 star에 있는 값을 사용하시면 되겠습니다.

**Comment by hyunggoo-kang** [comment]
@hanvic   `/action/stars/{cid}`  API의 star_average 값을 사용하시면 되는거죠? 

{
  "all": {
    "code": "v200045",
    "comment_count": 6,
    "created_at": "2018-11-09T15:19:31+09:00",
    "id": 107,
    "like_count": 4.7,
    "play_count": 29,
    "score": {
      "1": 1,
      "2": 1,
      "3": 2,
      "4": 4,
      "5": 4
    },
    "star_average": 3.8,
    "view_count": 1110
  },
  "my": {}
}

**Comment by Unk** [comment]
평점이 사용되는 곳이 총 세군데 있습니다.

1. 목록
2. 상세 페이지에서 상단 정보 영역
3. 상세 페이지에서 별점 영역

이 곳에서는 각각

1. `/contents/video-courses`
2. `/contents/video-courses/{id}`
3. `/contents/video-courses/{id}` (이번 요청으로 `/action/stars/{cid}`로 바뀔 예정)

의 정보들을 사용하고 있습니다.

1번과 2번 케이스에서는 `/action/stars/{cid}`의 값을 사용하지 않으므로 기존 메타 데이터는 여전히 사용되어야 합니다.

**Comment by hanvic** [comment]
네 해당 API에 있는 `meta` 값을 사용해주세요.
밖에 있는 review_count나 star_avg 같은 값들은 사라질 예정입니다.
star_set은 meta안으로 들어갈 예정이구요.

**Comment by nanuruya** [comment]
네 그럼 meta에 있는 정보로 적용되었으니 다음번 배포에서 확인하시면 문제 없을 것 같습니다.

**Comment by hanvic** [comment]
네 감사합니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1644-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1644-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550648922189400)

**Comment by hoonpapa** [comment]
Issue 개선 확인하였습니다.
추가적으로 테스트 진행후 Side이슈 발생시 신규등재하도록 하겠습니다.
