### ISSUE TITLE
[02/15][IOS][별점]디자인 별점 버전 기획서와 상이한 동작 정리

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#163]
[Test 환경]
Welaaa App ver: Welaaa 1.5.8(1522qa190215)
Device : iPhone6s+

1. 별점 등록 버튼 없음
2. 별점 등록후 수정/삭제 사양 추가 요청(사진 참조)
![issue](https://user-images.githubusercontent.com/45807513/52831315-882a6780-3117-11e9-9f61-a7e8535ba411.png)

**Comment by Unk** [comment]
0. **저희는 이 기획서를 전달 받은 적이 없습니다.**
1. 별점 등록 버튼은 디자인에 없습니다.

현재는 댓글 등록시에만 별점이 같이 등록되며 별도로 별점을 저장시키는 방법은 없습니다.

**Comment by hyunggoo-kang** [comment]
이 부분은 저희쪽에서 어떻게 동작하는지에 대한 내용과 버튼 디자인을 보내드리고 다시 요청드리도록 하겠습니다. 
@shj7831 @welaaa-sangyeon

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hoonpapa** [comment]
별점 이슈 상세 등제하기 위해서 현이슈 Closed합니다.
신규이슈 발생시 새로 등재하도록 하겠습니다.
