### ISSUE TITLE
[02/15][Android][이메일간편가입] 가입되어 있지않은 이메일로 가입 시 오류 메시지 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#164]
[Test 환경]
Welaaa App ver: [Android] ver 1.50.049(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
가입되어 있지않은 이메일로 가입시도 시 오류메시지가 발생하지만 가입하기 버튼을 누르게 되면 가입이 되어집니다.

[이슈 경로]
1. 이메일 간편가입
2. 가입되어 있지않은 이메일로 가입 시도
3. 오류 메시지 확인
4. [OK]후 가입하기 버튼 클릭 > 가입 성공
![0215](https://user-images.githubusercontent.com/45928019/52831471-20285100-3118-11e9-9a11-17fa83aafbd0.png)

**Comment by jungon-influential** [comment]
이메일 검증 시 응답을 잘 못 받을 경우 위와 같은 문구가 보일 수 있습니다.
문구를 '이메일이 확인을 성공하지 못했습니다' 로 수정해서 올바른 알림을 노출 하도록 하겠습니다.

**Comment by leejonghun92** [comment]
해당 이슈 재현되지 않습니다. 검증 완료 하였습니다.
