### ISSUE TITLE
[공통] iOS 구매 정책

### ISSUE THREAD

**Issue by welaaa-sangyeon** [smart-learning/design-2.0#165]
iOS는 클래스별 구매가 불가하여 아래와 같이 정책을 정하였습니다.
@jungon-influential 중온 과장님께서 덧글로 추가 정보를 말씀해주실 예정입니다.

![image](https://user-images.githubusercontent.com/44987455/52832561-6aabcc80-311c-11e9-9bf8-343683c7b64a.png)

**Comment by Unk** [comment]
옮겨옵니다.
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550213418110900?thread_ts=1550213113.106200&cid=GE1C2BEG5
```
김중온 [2 minutes ago]
if(platform.iOS && class-type){
    if (permission.type !== membership){
        if (currentMembership == null) {
            1번 경우    
        } else if (currentMembership == ‘오디오북 멤버쉽’){
            2번 경우        
        }
    }
}
```
