### ISSUE TITLE
[02/15][Android][오디오북] 구매하지 않은 오디오북의 기간문구가 0일로 나타나는 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#168]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test021302@qa.com / 1

[상세 내용]
구매하지 않은 오디오북(오리지널스)의 기간문구가 0일로 나타나게 됩니다.

[이슈 경로]
1. 로그인
2. 오디오북 중 "오리지널스" 클릭
3. 금액문구 옆 기간문구 확인
![021509](https://user-images.githubusercontent.com/45928019/52850713-7cf72c00-3157-11e9-8787-315761d5cca1.png)

**Comment by nanuruya** [comment]
구매하지 않은 오디오북 일때 구매정책상 날짜가 표시되는게 맞습니다. 
![image](https://user-images.githubusercontent.com/3823119/52851667-0c9dda00-315a-11e9-8315-f54b89160caa.png)
0일로 표시되는 부분은 api에서 보내주는 `rental_period` 값이 0 으로 넘어오기때문에 0일로 표시되고 있는 상태 입니다.
![image](https://user-images.githubusercontent.com/3823119/52851603-ebd58480-3159-11e9-9dd6-d356427624cc.png)
확인 부탁드립니다.

**Comment by hyunggoo-kang** [comment]
표시 방식에 대한 정리가 필요하므로 일단 삭제처리 하기로함. 이후 추가 할떄 Jira쪽 이슈로 생성필요
