### ISSUE TITLE
[02/18][Android][오디오북] 유료 오디오북 포스터의 재생 아이콘 클릭 시 다운로드 버튼이 바뀌는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#171]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0218@qa.com / 1

[상세 내용]
유료 오디오북 재생 아이콘 클릭 시 재생되지 않고 다운로드 버튼이 바뀌게 됩니다.

[이슈 경로]
1. 로그인
2. 유료 오디오북 임의로 클릭
3. 포스터의 재생 아이콘 클릭 
4. 다운로드 버튼이 첨부파일과 같이 변경 됨
![021803](https://user-images.githubusercontent.com/45928019/52924462-45af9780-3370-11e9-9929-e8389c4ccd7d.png)

**Comment by leejonghun92** [comment]
"내 문장이 그렇게 이상한가요?"에 대하여 콘텐츠 정상 재생 확인하였습니다.

**Comment by jungon-influential** [comment]
@Unk 확인 부탁드립니다.

**Comment by Unk** [comment]
저희가 어떤 부분을 확인해드리면 될까요?
위에 코멘트에서는 정상 재생 확인을 하셨다고 해서요.

**Comment by jungon-influential** [comment]
이슈는 '재생 버튼을 눌렀는데 다운로드가 진행되었다' 입니다.
재현부터 다시 해 봐야 할 듯 합니다.

**Comment by leejonghun92** [comment]
해당 이슈 재현되지 않습니다. 검증 완료 하였습니다. 재현되면 새로 등록하겠습니다.
