### ISSUE TITLE
[02/18][IOS][별점]멤버십 가입여부 상관없이 오디오북 구매버튼 미노출로 오디오북 구매할수없음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#172]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190218)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 오디오북 상세 페이지
3. 오디오북 개별 구매 버튼 미노출

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1858-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1858-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550570507168400)

**Comment by hoonpapa** [comment]
Issue 개선 확인하였습니다. Side Issue 발생시 신규 등재하도록 하겠습니다.
