### ISSUE TITLE
[02/18][IOS][별점]멤버십 가입후 3일동안 보지않기 팝업 미출력

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#173]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190218)
Device : iPhone6s+

1. 윌라 계정 로그인(멤버십 가입되어있는)
2. 3일동안 보지 않기 팝업 출력하는지 확인
3. 무료 계정일경우 팝업 정상 출력 멤버십 가입후 팝업 출력하지 않음

**Comment by hoonpapa** [comment]
AOS도 동일하게 동작하고 있습니다 확인 부탁드립니다.

**Comment by hoonpapa** [comment]
test072@qa.com 멤버십 X
test073@qa.com 프리미엄 멤버십
test074@qa.com 오디오북 멤버십 

가입되어있습니다 참조부탁드립니다.

**Comment by jungon-influential** [comment]
API 에서 받는 값이 없었기 때문에 정상 동작입니다.

**Comment by hoonpapa** [comment]
Issue확인하여 Closed합니다.
