### ISSUE TITLE
[02/18][IOS/AOS][별점]오디오북 전체목록 20번이후 21번이 아인 11번부터 시작되는 Issue

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#174]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190218)
Welaaa App ver: [Android] ver 1.60.001(02/15)_윌라디자인
Device : iPhone6s+, [Android] 갤럭시 7엣지

1. 윌라 계정 로그인
2. 오디오북 전체목록 보기 선택
3. 20번 이후 목록 보기시 21번이 아닌 11번으로 표시하는 Issue 발생
![833c6ed1-4e58-4689-9ceb-98fcb5ed2737](https://user-images.githubusercontent.com/45807513/52930783-32f78b80-338d-11e9-8018-38630675356b.png)

**Comment by hyunggoo-kang** [comment]
@hanvic API 상에서 주는 정보인지 확인이 필요합니다.

**Comment by nanuruya** [comment]
@hyunggoo-kang / 오디오북 전체목록 인기순서는 API에서 호출되는 부분이 아닙니다. 현재 코드 확인중 입니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hoonpapa** [comment]
issue 개선 확인하여 Closed합니다.
