### ISSUE TITLE
[2/19][공통] 매일 책한권 링크 영역 조정

### ISSUE THREAD

**Issue by hyunggoo-kang** [smart-learning/design-2.0#177]
현재는 매일 책한권의 "매일 책한권 보러가기" 버튼에만 링크가 걸려서 클릭할때만 이동하는데  이미지와 제목, 내용을 클릭해도 링크가 동작하도록 클릭 영역을 수정해주세요.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1521-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1521-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550557740154800)

**Comment by hyunggoo-kang** [comment]
확인되어 close 합니다.
