### ISSUE TITLE
[02/19][Android][오디오북] 오디오북 미리듣기 재생완료 후 다시 재생 시도 시 재생되지 않는 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#179]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0219@qa.com / 1

[상세 내용]
오디오북 임의의 콘텐츠 미리듣기 재생 완료 후 재생아이콘 클릭하여 다시 재생시도 시 재생되지 않습니다.
(Ex> 심리학이 서른 살에게 답하다)

[이슈 경로]
1. 로그인
2. 임의의 오디오북 콘텐츠 끝까지 재생
3. 재생완료 후 재생아이콘 클릭
4. 아무 반응 없음
![021904](https://user-images.githubusercontent.com/45928019/52992593-82ed5580-3454-11e9-85bd-98c2e3191566.png)

**Comment by hyunggoo-kang** [comment]
@leejonghun92 이건 github에서  close하고 jira에 다시 등록 바랍니다.

**Comment by leejonghun92** [comment]
W10-371로 이동하였습니다.
