### ISSUE TITLE
[02/19][Android][오디오북] 콘텐츠의 목차와 플레이어 리스트의 재생가능한 재생아이콘이 서로 다른 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#180]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/15)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0219@qa.com / 1

[상세 내용]
오디오북의 목차의 재생가능한 재생아이콘과 플레이어 리스트의 재생가능한 재생아이콘이 서로 상이합니다.
(Ex> 심리학이 서른 살에게 답하다)

[이슈 경로]
1. 로그인
2. 임의의 오디오북 목차의 재생아이콘 확인
3. 재생 후 플레이어 리스트의 재생아이콘 확인
4. 미리듣기의 콘텐츠만 재생아이콘이 있어야 될 것 같습니다.
![021905](https://user-images.githubusercontent.com/45928019/52992950-be3c5400-3455-11e9-9d2b-8d2e9fc076b9.png)

**Comment by hyukwoo** [comment]
design 이슈 아닌 건 jira 로 업데이트 요청 드립니다  .. 앞서 등록 해주신 내역들도 확인 부탁드립니다

**Comment by leejonghun92** [comment]
W10-370으로 이동
