### ISSUE TITLE
[02/19][Android][별점] 별점 등록 후 수정하면 평가그래프에 반영되지 않는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#181]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/19)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0219@qa.com / 1

[상세 내용]
클래스 콘텐츠에 별점을 등록 후 수정하면 평가그래프에 반영되지 않습니다. 뒤로가기 후 다시 평가그래프 확인 시 수정되지않고 기존에 등록한 별점 그대로 남아있게 됩니다.

[이슈 경로]
1. 로그인
2. 임의의 콘텐츠에 별점 5 등록
3. 등록 확인 후 별점 1로 수정
4. 평가그래프에 반영되지않음(*뒤로가기 후 다시 콘텐츠를 확인하면 처음에 등록한 별점이 남아있음)
![021907](https://user-images.githubusercontent.com/45928019/52996357-b7ffa500-3460-11e9-95bb-c1b1b13bd460.png)

**Comment by nanuruya** [comment]
평가그래프 반영 안되는 내융은 #162 와 동일한 이슈입니다. 

![image](https://user-images.githubusercontent.com/3823119/52996651-9652ed80-3461-11e9-8c7f-a5596ad0a0a4.png)
뒤로가기 후 다시 페이지 로드했을때 설정한 값이 아닌 처음 등록한 별점이 남아있는 이유는 
상세페이지에서 설정한 기본값이 반영되어서 그런것으로 확인되었습니다. 
다음 APK 전달에 반영하겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1643-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1643-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550562887162000)

**Comment by leejonghun92** [comment]
뒤로가기 후 다시 페이지 로드했을 때 설정한 값이 정상적으로 남아있는 부분 확인 하였습니다.
