### ISSUE TITLE
[02/19][Android][리뷰] 리뷰 등록 후 수정하고 수정한 리뷰를 삭제하게되면 등록이 되지 않는 현상 발생

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#182]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/19)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0219@qa.com / 1

[상세 내용]
클래스 콘텐츠에 리뷰 등록 후 수정하고, 수정한 리뷰를 삭제하면 문자데이터가 그대로 남아있습니다. 바로 등록버튼을 누르게되면 리뷰 입력요청 메세지가 발생합니다.

[이슈 경로]
1. 로그인
2. 임의의 콘텐츠 리뷰 등록 후 수정
3. 해당 리뷰 삭제 후 남은 문자데이터 확인
4. 바로 등록버튼 부르게 되면 리뷰요청 메세지 발생
![021908](https://user-images.githubusercontent.com/45928019/52996669-9e129200-3461-11e9-9494-dee6e30ef0dd.png)

**Comment by nanuruya** [comment]
특정 기기에서 데이터 바인딩 타이밍이 어긋나는것으로 확인되었습니다. 추가적인 처리 후 다음 APK 전달에 반영하겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-19-1643-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-19-1643-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550562887162000)

**Comment by leejonghun92** [comment]
해당 이슈 재현 되지 않습니다. 검증 완료 하였습니다.
