### ISSUE TITLE
[02/19][Android][별점] 별점 평균 그래프와 별점 그래프의 값이 서로 다른 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#183]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/19)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0219@qa.com / 1

[상세 내용]
별점 평균 그래프(★★★★★)와 별점 그래프의 값이 서로 다르게 나타나는 것 같습니다.

[이슈 경로]
1. 로그인
2. 임의의 콘텐츠 클릭
3. 별점 평균 그래프 값 확인
4. 별점 그래프 값 확인
![021909](https://user-images.githubusercontent.com/45928019/52998298-4d516800-3466-11e9-920f-042b5ec48c5f.png)

![021909-1](https://user-images.githubusercontent.com/45928019/52998303-4fb3c200-3466-11e9-92e4-f007710e6b15.png)

**Comment by hoonpapa** [comment]
ios에서 이슈 개선 확인하였습니다.
AOS는 신규버전을 받지 못해 확인 못하였습니다. AOS에서 이슈 재현될시 신규 등재하도록 하겠습니다.
Closed합니다.
