### ISSUE TITLE
[02/20][Android][리뷰] 클래스의 리뷰아이콘과 별점아이콘이 실제 등록된 리뷰 갯수, 별점 갯수와 상이한 현상 발생 

### ISSUE THREAD

**Issue by leejonghun92** [smart-learning/design-2.0#185]
[Test 환경]
Welaaa App ver: [Android] ver 1.60.001(02/19)_윌라디자인
Device : [Android] 갤럭시 7엣지
계정정보 : test0220@qa.com / 1

[상세 내용]
클래스의 리뷰아이콘과 별점아이콘이 실제로 등록된 리뷰 수와 별점 수에 맞지 않는 것 같습니다.
(EX> 리뷰아이콘 6 =/= 실제 등록된 리뷰 수 5, 
        별점아이콘 5 =/= 실제 등록된 별점 수 4 )

[이슈 경로]
1. 로그인
2. 임의의 클래스의 리뷰아이콘과 별점아이콘 확인
3. 해당 클래스 클릭
4. 등록된 리뷰 수와 별점 수 확인 후 비교
![022002-1](https://user-images.githubusercontent.com/45928019/53059045-dd3ff200-34f8-11e9-847e-4cd902d93d98.png)
![022002](https://user-images.githubusercontent.com/45928019/53059049-dfa24c00-34f8-11e9-823f-1c155c5b7117.png)

**Comment by hyunggoo-kang** [comment]
이 이슈는 close해주시고 jira로 이동해주세요.

**Comment by leejonghun92** [comment]
W10-376으로 이동하였습니다.
