### ISSUE TITLE
[02/20][IOS][클래스]멤버십 가입되어있지 않은 아이디로 클래스 상세페이지에서 멤버십 구매버튼 선택시 아무런 동작 하지 않음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#186]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인(멤버십 가입되어있지 않음)
2. 임의의 클래스 상세보기
3. 멤버십 구매버튼 선택
4. 멤버십 가입화면으로 전환되어야되나 아무런 동작 하지 않음
![img_0064](https://user-images.githubusercontent.com/45807513/53059578-aa96f900-34fa-11e9-883e-0095cf626a45.PNG)

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1306-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1306-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550635979176500)

**Comment by hoonpapa** [comment]
Issue 개선 확인하여 Closed합니다.
