### ISSUE TITLE
[02/20][IOS][댓글/별점]댓글/별정 등록시 등록 버튼을 빠르게 여러 번 입력시 하나의 별점/댓글이 입력한게 아니라 입력한 수만큼 별점/댓글이 입력됨

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#187]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스 상세보기
3. 댓글/별정 등록시 등록 버튼을 빠르게 여러 번 입력
4. 하나의 별점/댓글이 입력한게 아니라 입력한 수만큼 별점/댓글이 입력됨
5. 이후 별점수정시 마지막 입력된 별점만 수정됨(이전에 입력된 별점은 삭제도 안되고 수정도 할수없음)

![1](https://user-images.githubusercontent.com/45807513/53060106-9b18af80-34fc-11e9-8466-1f9f7ae875dc.png)

**Comment by hyunggoo-kang** [comment]
최초 입력 버튼 클릭후 response가 올때까지 버튼을 disable처리 등이 필요할것 같습니다.

**Comment by nanuruya** [comment]
4. 추가 등록이 안되도록 처리는 되어있습니다. 다시한번 확인해보겠습니다.
5. 수정을 위해서는 수정 버튼을 눌러야 수정모드로 변경됩니다. 별점은 삭제되지 않는게 맞습니다.

**Comment by hoonpapa** [comment]
별점도 3개가 등록이 되어 나타나는 이슈 입니다. 위의 이슈가 발생하지 않으면 나오지 않은 이슈이니 확인 부탁드립니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1306-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1306-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550635979176500)

**Comment by hoonpapa** [comment]
Issue 개선확인하여 Closed합니다.
