### ISSUE TITLE
[02/20][IOS][댓글/별점]댓글 삭제시 "삭제하겠습니까" 팝업 출력하지 않고 바로 삭제됨 기획서와 상이함 

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#188]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스 상세보기
3. 임의의 댓글 입력
4. 입력한 댓글 삭제버튼 선택
5. 삭제하겠습니까" 팝업 출력하지 않고 바로 삭제됨
![q](https://user-images.githubusercontent.com/45807513/53060340-7a9d2500-34fd-11e9-9171-d2d52b443ad7.png)
제됨

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1306-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1306-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550635979176500)

**Comment by hoonpapa** [comment]
Issue개선되어 Closed합니다.
