### ISSUE TITLE
[02/20][IOS][댓글/별점]5개 이상 리뷰 입력되어있는 리뷰 확인시 더보기 선택하여도 이전에 입력한 리뷰 확인할수없음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#190]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스 상세보기(리뷰 5개 이상 입려 되어있는 클래스)
3. 더보기 선택하여도 이전에 입력한 리뷰 확인할수없음
![img_0073](https://user-images.githubusercontent.com/45807513/53061077-03b55b80-3500-11e9-88a3-e6d0f38ecc3e.PNG)

**Comment by hyunggoo-kang** [comment]
API쪽의 문제면 이야기 해주시기 바랍니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1306-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1306-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550635979176500)

**Comment by hoonpapa** [comment]
Issue 개선 되어 Closed합니다
Side Issue 발생하여 신규 이슈로 등재하도록 하겠습니다.
