### ISSUE TITLE
[02/20][IOS][댓글/별점]처음 리뷰 등록후 수정시 키보드가 리뷰화면을 가려 글씨를 확인할수없음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#191]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스 상세보기(리뷰 달려있지 않은 클래스/오디오북)
3. 임의의 댓글 입력
4. 수정시 키보드가 리뷰입력 화면을 가림
![1231](https://user-images.githubusercontent.com/45807513/53061508-357af200-3501-11e9-8ad6-e42c7c6745e9.png)

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1306-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1306-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550635979176500)

**Comment by hoonpapa** [comment]
@nanuruya  Issue 미개선 되었습니다 확인 부탁드립니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1644-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1644-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550648922189400)

**Comment by pro9rammer** [comment]
@nanuruya IOS 에서만 발생하고 있습니다.

**Comment by Unk** [comment]
KeyboardAvoidingView 의 동작이 정확하게 픽셀을 정해서 동작하는게 아닌 만큼 키보드가 나오기 전 TextInput이 화면 아래 끝선에 걸려있다든가 하는 상황에서는 Avoiding 동작 후에도 키보드 영역에 일부 걸려있는 정도로 표시되거나 하는 정도의 문제는 있습니다.

다만 키보드 뒤로 TextInput 이 들어가 스크롤을 해도 나오지 않는다던가 하는 문제는 발생하지 않습니다.

**Comment by pro9rammer** [comment]
@Unk 예 참고하도록 하겠습니다~

**Comment by hoonpapa** [comment]
Issue 개선 확인하였습니다.
