### ISSUE TITLE
[02/20][AOS/IOS][댓글/별점]리뷰입력시 리뷰에 적힌 시간과 핸드폰 시간이 일치 하지 않음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#192]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스 상세보기
3. 임의의 리뷰 입력
4. 리뷰 입력시간과 핸드폰에 입력시간이 상이함
![img_0077](https://user-images.githubusercontent.com/45807513/53062127-17ae8c80-3503-11e9-9d21-2bae2577d64a.PNG)
안드로이드도 동일한 현상 발생

**Comment by hyunggoo-kang** [comment]
@hanvic  utc로 표기되는게 아닌가 싶습니다.

**Comment by leejonghun92** [comment]
[AOS]도 동일한 이슈 발생합니다.
![022003](https://user-images.githubusercontent.com/45928019/53062279-a91dfe80-3503-11e9-84f4-4b052f1706cc.png)

**Comment by hyunggoo-kang** [comment]
서버쪽에서는 KST 시간을 내려주는것으로 확인됩니다. 클라이언트쪽 확인 바랍니다.

**Comment by nanuruya** [comment]
네 확인 해보겠습니다.

**Comment by nanuruya** [comment]
API에서 UTC 오프셋이 +09:00 으로 안오고 +00:00 으로 오고 있습니다. 
`created_at: "2019-02-20T14:29:24+00:00"`

![image](https://user-images.githubusercontent.com/3823119/53068969-aaf4bb80-351d-11e9-85fd-f48d95b3b6e5.png)

**Comment by hyunggoo-kang** [comment]
저희쪽에서 확인해보도록 하겠습니다.

**Comment by jungon-influential** [comment]
포맷이 `'YYYY. MM. DD hh:mm'` 이렇게 되어 있던데 `HH:mm`, `hh:mm a` 형태가 되어야 할 듯 한데 확인 부탁드립니다.

**Comment by hanvic** [comment]
+09:00으로 표시되도록 수정하여 배포중입니다.

**Comment by hanvic** [comment]
배포완료되었습니다. 확인바랍니다.

**Comment by hanvic** [comment]
지금 댓글을 남기면 03시로 표시되고있는데 15시로 표시되도록 수정요청드립니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1644-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1644-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550648922189400)

**Comment by Unk** [comment]
가능하시면 이 이슈 먼저 확인해주실 수 있을까요?
저희쪽으로 분류된 마지막 이슈라서 본 이슈가 클로즈 되는걸 작업자들이 대기하고 있는 중이라서요 😄

**Comment by leejonghun92** [comment]
해당 이슈 검증 완료 하였습니다.
