### ISSUE TITLE
[02/20][AOS/IOS][댓글/별점]5개이상 리뷰달려있는 클래스/오디오북 리뷰 더보기 선택후 리뷰 등재시 5개 이상 등재되어있는 리뷰 보이지 않음 

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#196]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 클래스/오디오북 상세화면(리뷰 5개 이상 달려있는)
3. 리뷰 더보기 선택
4. 임의의 리뷰 입력
5. 리뷰 입력후 5개이상 리뷰목록을 볼수 없음
![1](https://user-images.githubusercontent.com/45807513/53068588-5ac92980-351c-11e9-848f-e68e5eadf9b7.png)

**Comment by Unk** [comment]
1. 윌라 계정 로그인
1. 임의의 클래스/오디오북 상세화면(리뷰 5개 이상 달려있는)
1. 리뷰 더보기 선택
1. 임의의 리뷰 입력
1. 리뷰 입력후 5개이상 리뷰목록을 볼수 없음

의 순서로 재현시 더보기 버튼 정상 출력되고 동작 확인 했습니다.
해당 오류를 유발하는 다른 원인이나 재현경로가 있을 것으로 생각됩니다.

짐작가는 부분이 있는 것이,

디버그 모드로 실행중이며 Debug JS Remotly 가 선택되어 있을 경우 ajax 호출의 주체가 앱 내의 번들이 아닌 리모트의 메트로 번들러가 되고 메트로 번들러는 CORS 샌드박스 정책의 영향을 받게 됩니다.
CORS 샌드박스의 영향을 받을 경우 2xx 응답을 받더라도 Response Header가 `Content-Type` 등의 최소한의 헤더만 보여주고 `X-*`류의 커스텀 헤더가 노출되지 않을 수 있습니다. `Pagination-*` 헤더들도 커스텀 헤더에 해당하므로 해당 정책의 영향을 받을 경우 노출되지 않을 수 있습니다.
(물론 지금 올려주신 스크린샷의 경우 전송 전에는 표시가 되고 있기 때문에 CORS 문제가 아닐 수도 있습니다.)

비슷한 이슈: https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields

**Comment by Unk** [comment]
디버그 모드로 인한 문제가 아닌지 확인 요청드립니다.
저희쪽에서는 디버그 활성화시 재현되고 끄면 재현되지 않습니다.

**Comment by hyunggoo-kang** [comment]
일단 재현된 디바이스가 디버그 모드는 아닙니다.

**Comment by Unk** [comment]
Swagger와 Curl 호출상에서는 `Pagination-*` 헤더들이 확인 되지만 실제 디바이스에서 호출시에는 누락되는 현상이니 API 파트에서도 같이 확인을 부탁드립니다. @hanvic

**Comment by Unk** [comment]
@hanvic  현재 앱단에서 `Pagination-Has-Next` 등의 헤더가 찍히지 않는 문제가 발생하는 것 같습니다.
`더 보기`버튼의 출력 여부는 헤더 값에 따라서 표시하거나 안하도록 해놓은 상태입니다.

혹시 이게 `Access-Control-Expose-Headers` 헤더에 대한 문제라면 API에서 `Access-Control-Expose-Headers`에 대한 헤더를 추가로 보내주실 수 있을까요?

**Comment by hanvic** [comment]
Access-Control-Expose-Headers에 추가 가능한지 확인하고 있습니다.

**Comment by hanvic** [comment]
`Access-Control-Expose-Headers` 에 `Pagination-Has-Next,Pagination-Current-Page,Pagination-Next-Page,Pagination-Per-Page,Pagination-Total` 포함해서 다시 배포하고 있습니다.

**Comment by pro9rammer** [comment]
@Unk 댓글 등록 후 더보기 버튼이 정상적으로 노출되고 있고 더보기 누르면 콘텐츠도 가져오는것으로 확인되는데 이상없는지 확인요청드립니다.

**Comment by hoonpapa** [comment]
더보기 이후 리뷰를 등재하면 더보기 댓글이 사라지는것이 이슈입니다.
확인 부탁드립니다.

**Comment by hoonpapa** [comment]
이슈 개선 확인하였습니다 Closed하겠습니다.

**Comment by hoonpapa** [comment]
수정선택후 글씨를 다른글씨로 작성후 등록시 더보기가 
나오지 않습니다. 다시한번 확인 부탁드립니다.

**Comment by leejonghun92** [comment]
[AOS]도 동일한 이슈 발생하였습니다.

**Comment by Unk** [comment]
혹시 저희 재현 방법이 잘못된 부분이 있나 싶어 확인차 영상 첨부 드립니다.

https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550721016004300?thread_ts=1550716891.004100&cid=GE1C2BEG5

1. 내 댓글이 있는 컨텐츠
2. 내 댓글 수정
3. 더보기 나타남. 동작함
4. 내 댓글 다시 수정
5. 더보기 나타남. 동작함

혹시 다른 시도를 해봐야 더보기가 안나오는 경우가 생길까요?
확인 부탁드립니다.
감사합니다.

**Comment by Unk** [comment]
Android의 경우입니다. (안드로이드 기기가 노후해 녹화에는 에뮬레이터를 사용했습니다.)

https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550721556004900?thread_ts=1550716891.004100&cid=GE1C2BEG5

**Comment by leejonghun92** [comment]
1. 댓글이 5개 이상인 콘텐츠 클릭 ("수포자인 저도 수학이 필요한 순간이 있을까요?"

**Comment by leejonghun92** [comment]
1. 댓글이 5개 이상인 콘텐츠 클릭 ("수포자인 저도 수학이 필요한 순간이 있을까요?"
2. 댓글 더보기 클릭
3. 댓글 남기기
4. 더보기 사라짐 "확인"
5. 홈화면 갔다가 다시 해당 콘텐츠 클릭
6. 더보기 펼쳐놓고 내 댓글 수정 후 등록 
7. 더보기 사라짐 "확인"
8. 홈화면 갔다가 다시 해당 콘텐츠 클릭
9. 더보기 펼쳐놓고 내 댓글 삭제
10. 더보기 사라짐 "확인"

**Comment by Unk** [comment]
더보기가 사라진다는 것이

1. 더보기 버튼이 사라짐
2. 5개에서 10개로 펼쳤는데 댓글 작성/수정시 다시 5개로 줄어듬

중 어느 현상을 말씀하시는 건가요?

댓글 작성/수정시 작성한 댓글만 갱신하는 것이 아니고 전체 댓글을 다시 처음부터 로드하기 때문에 2번은 정상 동작입니다.

**Comment by leejonghun92** [comment]
1. 더보기 버튼이 사라짐 현상입니다. 첨부사진 보시면 더보기 버튼이 아예 없어집니다.
![022103](https://user-images.githubusercontent.com/45928019/53143752-c07cea80-35dc-11e9-9707-b38c80065122.png)

**Comment by Unk** [comment]
재현 경로 찾았습니다.
더보기를 누를 때 더 이상 더보기가 나오지 않을 때 까지 더보기를 눌러서 한번 사라지고 나면, 그 이후에는 등장하지 않습니다. 반드시 끝까지 더보기를 눌러야만 발생하는 이슈였습니다.
저희쪽에서 테스트 한 명견만리쪽은 댓글이 많아 더보기를 끝까지 펼치지 않았기 때문에 재현되지 않았습니다.

재현경로 외에 원인도 찾아 수정하고 있습니다.

**Comment by nanuruya** [comment]
리뷰 더보기 표시 수정된 APK 아래 링크에서 확인 가능합니다.
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550726618006300

**Comment by leejonghun92** [comment]
[AOS] 검증 완료 하였습니다.

**Comment by hoonpapa** [comment]
Issue개선 확인하여 Closed합니다.
