### ISSUE TITLE
[02/20][IOS][오디오북]오디오북 리스트 버튼이름 가운되정렬되지 않고 위로 올라가있음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#197]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 임의의 오디오북 리스트 화면
3. 리스트 버튼 이름이 가운데 정렬되지 않고 위로 올라가있음(사진 참조)
![img_0083](https://user-images.githubusercontent.com/45807513/53072153-b51bb780-3527-11e9-9724-cf5307c9eb73.PNG)

**Comment by nanuruya** [comment]
뱃지 정렬 코드가 빠져있는것으로 확인되었습니다. 다음 APK에 수정 포함됩니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1644-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1644-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550648922189400)

**Comment by hoonpapa** [comment]
issue 개선 확인하였습니다.
