### ISSUE TITLE
[02/20][IOS][오디오북]오디오북 이달의책 부분 선택시 선택이 잘되지 않음

### ISSUE THREAD

**Issue by hoonpapa** [smart-learning/design-2.0#198]
[Test 환경]
Welaaa App ver: Welaaa 1.6.1(1601qa190220)
Device : iPhone6s+

1. 윌라 계정 로그인
2. 오디오북 이달의 책 영억 선택 (사진 참조)
3. 선택이 잘되지 않음 앱 초기 실행후 자주 발생
![img_0085](https://user-images.githubusercontent.com/45807513/53078169-fc5d7480-3536-11e9-9f00-294b2829c5df.PNG)

**Comment by hyunggoo-kang** [comment]
1. 책 이미지의 클릭영역이 작은 느낌인데요, 확인이 필요합니다.
2. 책 하단의 텍스트와 리딩멘트 부분 이미지, 텍스트에도 링크를 걸어주시면 좋겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1803-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1803-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550653664192800)

**Comment by hoonpapa** [comment]
이슈 재현되고있습니다
영영 issue가 아닌거같습니다.

**Comment by hyunggoo-kang** [comment]
디바이스마다 100% 발생하는 이슈는 아니라서 일단 진행을 하고 추후 개선을 하도록 하겠습니다.

**Comment by Unk** [comment]
범위를 조정하긴 했지만 조정하기 전에도 저희는 전혀 재현이 되지 않던 문제라서 모든 기기에서 재현되는 것이 아닐거란 생각이 드는데요,
혹시 디버그 모드에서 테스트 하고 계신가요?

**Comment by hyunggoo-kang** [comment]
일단 재현된 디바이스가 디버그 모드는 아닙니다.

**Comment by Unk** [comment]
모든 기기에서 발생하지 않는다면 현재 문제가 발생하는 것이 확인된 기기는 이슈에서 말씀하신 iPhone 6S+ 인가요?
저희쪽에서 확인한 기기는 XS와 X입니다.

**Comment by hyunggoo-kang** [comment]
재현된 폰은 iPhone6s+ 이고, 저희쪽에서도 고사양폰에서는 재현빈도가 낮고 저사양폰에서 주로 발생합니다.

**Comment by nanuruya** [comment]
TouchableOpacity 가 원인불명으로 터치가 되지 않아 TouchableOpacity 안으로 패딩을 이전하는것으로 수정하였습니다.

**Comment by nanuruya** [comment]
`welaaa-1.60.001-2019-02-20-1922-design-release.apk` 빌드버전에 적용되었습니다.

##APK 확인 링크
welaaa-1.60.001-2019-02-20-1922-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550658575196800)

**Comment by hoonpapa** [comment]
iphone6S +에서는 계선이 어느정도 된거 같습니다. (간혹 안될때도 있습니다.)
iphone Se 에서는 책이미지를 선택할경우 아예 터치 동작을 하지 않습니다.
아래부분 텍스트를 터치를 하면 그나마 터치가 되고 있습니다.
확인 부탁드립니다.

**Comment by Unk** [comment]
SE는 본 프로젝트의 지원 범위가 아닙니다

**Comment by hyunggoo-kang** [comment]
꼭 SE쪽이 아니더라도 다른폰에서도 100% 터치가 잘 되지는 않아서 원인파악 및 해결은 해야 할것 같습니다. 저희쪽에서도 같이 보고 있으니 함께 봐주시면 감사하겠습니다.

**Comment by Unk** [comment]
스크롤시 카테고리의 위치 조정에 `transform` 스타일 속성을 이용하는 부분이 `untouchable area`를 만드는 이슈가 있어 `top` 속성으로 이동하도록 변경했습니다.
`transform`에 비해서 `top`이 더 느리게 동작합니다만 터치가 안되는 영역이 생기는 것이 더 큰 이슈일테니...

PR 보냈고 빌드는 곧 전달 드리겠습니다.

**Comment by Unk** [comment]
APK 전달 드립니다.

https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550731290008600

**Comment by hoonpapa** [comment]
동일한 동작이 계속 재현되고있습니다.
다시한번 확인 부탁드립니다.

**Comment by nanuruya** [comment]
`react-native-snap-carousel` 의 Stack 옵션이 IOS에서 스크롤한 화면 위치에 따라서 터치 이벤트가 동작하지 않는 버그가 있는것으로 확인되었습니다. 레이아웃 옵션을 Default로 변경하여 적용해야할것같습니다. 
Default 옵션으로 변경하면 터치 이벤트 오류가 발생하지 않습니다. 
Default 옵션으로 인해 변경된 레이아웃은 아래 이미지와 같습니다. 확인 부탁드립니다.
![img_f6655aa41158-1](https://user-images.githubusercontent.com/3823119/53159165-a6590180-3608-11e9-8415-d35251102fc5.jpeg)

**Comment by Unk** [comment]
추가로...
신규 환경을 만들어서도 테스트를 해보았는데
`ScrollView` > `Stack Swiper(snap-carousel)` > `Slide` > `TouchableOpacity` 구성일 때 터치 범위 오류가 발생합니다.

![img_0618](https://user-images.githubusercontent.com/2232142/53207142-439e4f00-3676-11e9-81cc-bbb9c842cecb.PNG)

이정도 위치에서는 이미지가 터치가 됩니다.

![img_0619](https://user-images.githubusercontent.com/2232142/53207154-4d27b700-3676-11e9-82f4-df51e7a905a8.PNG)

이정도 스크롤 하고나서는 터치가 안됩니다.

`react-native-snap-carousel` 자체의 문제는 아닌 것 같고 `stack` 타입 한정으로만 있는 버그로 보입니다.
해당 이슈는 `react-native-snap-carousel` 쪽에 이슈로 발행하고 `default`로 변경하는 것이 좋을 것 같습니다.

default 로 적용된 내용은 apk로 먼저 전달드리고, 확인하신 후 변경하는 내용이 적용되면 코드 푸시하고 PR토록 하겠습니다.

**Comment by Unk** [comment]
APK

https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550789858009900

**Comment by hyunggoo-kang** [comment]
개선 확인되어 close 합니다. 수고하셨습니다.
