### ISSUE TITLE
[메인] 메뉴바 수정  

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#2]
![image](https://user-images.githubusercontent.com/3823119/48414312-b18ccd80-e78d-11e8-9031-4e6fca0491b7.png)

배경 윌라 컬러로 변경 (버튼으로 명확히 구분되게 디자인)

**Comment by welaaa-sangyeon** [comment]
190131_1.50.050.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52045409-d2441280-2587-11e9-8842-28db56bea66b.png)

**Comment by nanuruya** [comment]
welaaa-1.50.049-2019-02-02-1034-design-release 빌드버전에 적용되었습니다.

APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)
