### ISSUE TITLE
[메인 > 배너] UI 변경

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#3]
### 기존 디자인
![image](https://user-images.githubusercontent.com/3823119/48414387-e8fb7a00-e78d-11e8-9d47-6911a52cc733.png)

### 참고 시안
![image](https://user-images.githubusercontent.com/3823119/48414405-fc0e4a00-e78d-11e8-8690-3e5160bf80bb.png)
![image](https://user-images.githubusercontent.com/3823119/48414410-00d2fe00-e78e-11e8-9e94-bbb43346bb3c.png)

**Comment by welaaa-sangyeon** [comment]
Dot 컬러 > white 30%
 ㄴ 클래스,오디오북 상세페이지의 소개카드 부분과 동일

![image](https://user-images.githubusercontent.com/44987455/50868451-ecf4f280-13f2-11e9-8958-e253d145a529.png)

**Comment by welaaa-sangyeon** [comment]
배너 갯수 표현 방법 변경

(App_class_메인페이지_190115_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51160146-fb9a4880-18cf-11e9-9829-84588dfcfb1f.png)
