### ISSUE TITLE
[메인 > 오디오] 이달의책 수정

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#33]
- [x] 레이아웃 변경
- [x] 배경 컬러 변경
- [x]  최근 3개월치만 노출되게 수정 

![image](https://user-images.githubusercontent.com/3823119/49780030-326cc400-fd50-11e8-89bc-e0179ad18f48.png)

**Comment by nanuruya** [comment]
노출하는 방식 관련하여 내용 추가 부탁드립니다.

**Comment by welaaa-heejae** [comment]
확인이 늦어졌습니다.
말씀하신 부분은 최근 3개월 내용만 보여주는 식으로 결정되었습니다.
디자인은 저희가 전달드린 디자인으로 적용해주세요~:)

**Comment by nanuruya** [comment]
## XD 버전
App_audio_메인페이지_190115_confirm.xd

## 문의 내용
![image](https://user-images.githubusercontent.com/3823119/51160396-1caf6900-18d1-11e9-942d-e1b52e4b9b61.png)

https://github.com/smart-learning/design-2.0/issues/121#issuecomment-454271449 코멘트와 동일한 이유로 재작업 공수를 줄이기 위해 서버에서 주실 수 있는 형태의 목업 json 을 기준으로 작업하도록 하겠습니다. @jungon-influential

**Comment by welaaa-sangyeon** [comment]
하단에 들억어가는 리딩멘토 이미지 모음입니다

[리딩멘토 이미지 모음.zip](https://github.com/smart-learning/design-2.0/files/2762015/default.zip)

**Comment by Unk** [comment]
> 하단에 들억어가는 리딩멘토 이미지 모음입니다
> 
> [리딩멘토 이미지 모음.zip](https://github.com/smart-learning/design-2.0/files/2762015/default.zip)

리딩 멘토 이미지는 API를 통해서 주소를 전달받게 되는 것 아닌가요?
파일을 따로 첨부해 주셔서 혹시 API를 통해서 받는 것이 아닐 수도 있나 싶어서 문의 드립니다.

**Comment by welaaa-sangyeon** [comment]
@Unk 
API를 통해 받아야 하는게 맞습니다.
그로테스큐와 더불어 김중온 과장님께도 공유드려야 하여 올려두었습니다.

**Comment by welaaa-sangyeon** [comment]
오디오북 썸네일이 변경되어 UI를 변경하였습니다.

(App_audio_메인페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51240483-21524b00-19bf-11e9-8893-55ee208ff991.png)

**Comment by nanuruya** [comment]
리딩멘토 사진 이미지 관련된 부분은 아래 링크와 동일한 이슈입니다. 
https://github.com/smart-learning/design-2.0/issues/38#issuecomment-459345777

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

리딩멘토 이미지 교체 관련 내용은 
(https://github.com/smart-learning/design-2.0/issues/38#issuecomment-459345777) 코멘트 확인 부탁드립니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
@jungon-influential 
아래의 컬러를 적용해주세요

![image](https://user-images.githubusercontent.com/44987455/52396273-a62f1100-2af4-11e9-9ba1-0d28b165c095.png)

1. #E0AD62
2. #D37370
3. #D9C44E
4. #CEA86B
5. #C4769A
6. #CBB111
7. #81B960
8. #8078B5
9. #7D9CC9
10. #D38A60
11. #D1AD8B
12. #DE897C

**Comment by jungon-influential** [comment]
@nanuruya 이달의 책 순서가 맞지 않습니다. API는 순서대로 보내고 있습니다. 확인 부탁 드립니다.

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52710885-d9c9d980-2fd3-11e9-96f1-c937a0a9a801.png)

**Comment by welaaa-sangyeon** [comment]
12월 부분 최하단 텍스트가 없는 이슈는 서버 자체에 내용이 없어 그런것으로 확인되었습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
