### ISSUE TITLE
[메인 > 오디오북] 매일책한권 수정

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#34]
![image](https://user-images.githubusercontent.com/3823119/49780171-ac04b200-fd50-11e8-80e7-a9de17331bcf.png)

**Comment by welaaa-sangyeon** [comment]
UI가 기존보다 간결하게 변경되었습니다

(App_audio_메인페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51240677-932a9480-19bf-11e9-8e9c-b805196c9a14.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52054315-71c0cf80-259f-11e9-941d-7f1e9cf5316e.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk

책제목 두줄 확인 완료.
서브 타이틀의 내용은 저자가 아닌 한줄 카피로 변경
![image](https://user-images.githubusercontent.com/44987455/52402101-bb14a000-2b06-11e9-87b3-bc0b21231c43.png)

**Comment by nanuruya** [comment]
@welaaa-sangyeon / 오디오북 전체목록쪽 캡쳐주신것같은데 확인 부탁드립니다. :)

**Comment by welaaa-sangyeon** [comment]
해당 내용을 넣어주시면 된다는 예시입니다^^

**Comment by nanuruya** [comment]
매일 책한권 API에서 보내주는 정보에서는 한줄카피를 표시할 수 없습니다. 
현재 아래와 같이 데이터가 넘어오는데요, memo쪽 텍스트를 변경하거나, subtitle 텍스트를 추가해주시면 될것같습니다. 
``` 
 "category": [    "월",    "화",    "수",    "목",    "금"  ],
  "금": [
    {
      "cid": "z100005_040",
      "hit_count": 0,
      "id": 22743,
      "image": "http://static.welaaa.co.kr/static/courses/z100005/z100005_040_wide_clip.jpg",
      "memo": "<br>김애란 지음 | 문학동네 출간 | <br><br>시간의 흐름을 따라가지 못하고 제자리에 멈춰 서버린 이들을 위한 김애란의 문장들.",
      "open_date": "2019-02-01",
      "review_count": 0,
      "star_avg": 0,
      "title": "<바깥은 여름> 안과 밖의 시차"
    },
...
```

**Comment by jungon-influential** [comment]
`"title"` 값에서 <> 제외한 문구 넣으시면 됩니다.

**Comment by Unk** [comment]
`welaaa-1.50.050-2019-02-08-0943-design-release.apk`  
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549586788018200

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52710685-4e504880-2fd3-11e9-933a-b4859ae16c0e.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

디자인 수정 감사합니다.
- 버튼 터치시 북리뷰 카테고리로 가는 것은 확인하였으나 '인기'가 아닌 '업데이트 순' 페이지로 이동되어야 할 것 같습니다
