### ISSUE TITLE
[오디오북 > 목록] 오디오북 컴포넌트 수정

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#37]
- [ ] 3D 썸네일이 아닌 2D 썸네일을 활용한 디자인
- [ ] 컴포넌트 별 명확하게 분리되는 디자인 ( 더 보기 삭제, 스크롤시 자동으로 펼침 기능 추가 )
- [ ] 가격 표기 수정 ( 0원일 경우 0원이 아니라  ‘무료’로 표기 / 현재 오디오북 무료 콘텐츠:  북리뷰 전체  )
- [ ] 콘텐츠의 기본 정보만 노출: 제목, 저자 (또는 리딩멘토), 러닝타임, 가격 (리스트에서는 소개글 제외하는 방법 고민)
- [ ] 아이콘 추가 (종류별)
	> 추천
	> new
	> 독점
	> 유료/무료 (현재는 무료만 표기)

![image](https://user-images.githubusercontent.com/3823119/48417130-52cb5200-e795-11e8-97bb-afb46563ff8b.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52054864-2a3b4300-25a1-11e9-8d99-c8c728f77a5c.png)

**Comment by nanuruya** [comment]
컴포넌트 노출정책 수정한 내용먼저 
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.
나머지 수정사항은 다음 빌드 버전에 적용됩니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

노출 정책(20개 노출, 스크롤시 추가로 20개)이 명확하게 적용되지 않은 것 같습니다.
카테고리별로 다른 것 같기도 한데, 확인 한번 부탁드립니다.

**Comment by welaaa-sangyeon** [comment]
로드가 안되는건 아니구요, 갯수가 다른것 같습니다

**Comment by Unk** [comment]
갯수는 API에서 정해서 내려주고 개수를 요청해서 받을 수는 없습니다.
기획상 20개로 결정되어 API에서도 해당 내용을 반영해주는 것으로 생각했는데 아니었나보네요.
내부에서도 이 내용이 공유되신게 아니라면 API에서 20개씩 보내주도록 요청이 필요합니다. @jungon-influential

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-02-08-0915-design-release.apk 기준

- 리스트 페이지에서 서브 카피가 두줄일 경우 뱃지와 겹치는 것을 발견하였습니다.
   최종 전달된 xd에서 텍스트 사이즈와 글자간의 간격들을 확인해주시길 부탁드립니다.

![2](https://user-images.githubusercontent.com/44987455/52458986-e5696a80-2ba5-11e9-9b85-e74773a35cb0.png)

**Comment by jungon-influential** [comment]
API 에서는 페이지당 10개씩 내리고 있습니다.
페이지당 20개씩 내리도록 수정하겠습니다.
추가로 80개를 넘어가는 시점부터는 10개당 로딩 프로그래스가 보입니다.
80개 이전에는 빨리 노출되는 이유를 디버깅 모드로 네트워크 호출이 정상적으로 되는지 확인 필요할 듯 보입니다.

**Comment by Unk** [comment]
로딩이 늦어져서 프로그레스가 보이는 상황이 생기는 건가요?
아니면 프로그레스만 나오고 로딩이 안되는 현상이 생기는 건가요?

**Comment by jungon-influential** [comment]
로딩이 안되는 현상을 말씀 드리는 건 아닙니다.
페이지당 20개로 수정을 한 뒤에 몇 개나 미리 로드되는지 디버깅 부탁 드립니다.
수정 뒤에 말씀 드리겠습니다.

**Comment by jungon-influential** [comment]
queryparam: count=20 주시면 될 듯 합니다.
수정하시고 디버깅 결과 공유 부탁 드립니다.

**Comment by Unk** [comment]
https://api-prod.welaaa.com/api/v1.1/contents/audiobooks?page=1&sort=hot&count=20

count=20 해도 10개씩만 옵니다

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-11-1726-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-11-1726-design-release.apk  
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549874072008300)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![default](https://user-images.githubusercontent.com/44987455/52710631-23fe8b00-2fd3-11e9-99c8-5238929c3460.png)

**Comment by nanuruya** [comment]
뱃지의 `height` 때문에 타이트해보이는것으로 보입니다.
뱃지 `height`가 최초 디자인엔 35dp였지만 일괄 적용 하는 부분에서 40dp로 변경되었습니다. 
해당 컴포넌트만 다시 35dp로 적용해놓겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
별점아이콘이 하트아이콘으로 롤백되었습니다.
