### ISSUE TITLE
[메인 > 오디오북 - 이달의책 > 상세] 수정

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#38]
- [ ] 배경 삭제
- [ ] 좌측 정렬
- [ ] 버튼 리디자인
- [ ] 아이콘 삭제
- [ ] 이달의 책 상세 보기 > 네이밍 변경
![image](https://user-images.githubusercontent.com/3823119/48417453-26fc9c00-e796-11e8-914e-940742485d16.png)

- [ ] 클래스 > 상세 페이지와 같은 디자인, 정책 ( #22 )
![image](https://user-images.githubusercontent.com/3823119/48417501-47c4f180-e796-11e8-98bb-df4be9553c4b.png)

- [ ] 클래스 > 상세 페이지와 같은 디자인 ( #20 )
![image](https://user-images.githubusercontent.com/3823119/48417518-53181d00-e796-11e8-9631-ad936845f6fe.png)

- [ ] 버튼 디자인 변경, 아이콘 삭제
![image](https://user-images.githubusercontent.com/3823119/48417530-58756780-e796-11e8-994d-d0174ed09c53.png)

**Comment by welaaa-sangyeon** [comment]
이달의책 상세페이지 UI 변경

(App_audio_이달의책_190110.xd)

![app_audio_ _190110](https://user-images.githubusercontent.com/44987455/50958264-a7741a80-1503-11e9-939e-b1d35a04ad57.png)

**Comment by welaaa-sangyeon** [comment]
이달의책 상세페이지 UI 변경

(App_audio_이달의책 상세페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51243575-439b9700-19c6-11e9-8519-a1cc3b1265d0.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52054774-e0eaf380-25a0-11e9-80e4-cdc02a826ba9.png)

**Comment by nanuruya** [comment]
리딩멘토 소개 > 리딩멘토 이미지 관련
![image](https://user-images.githubusercontent.com/3823119/52057373-31198400-25a8-11e9-80fe-3c32640ff20c.png)

해당 부분 API에서 보내주는 이미지를 사용하고있습니다. 
API에서 보내주는 이미지 업데이트 해주시면 정상 표시 됩니다.
참고로 API에서 `...teacher.images.profile`을 사용했습니다. 
혹시 API 가 업데이트 된다면 해당 값을 알려주시면 교체하겠습니다. 
```
...
"teacher": {
          "headline": null,
          "id": 7,
          "images": {
            "default": "...",
            "profile": "..."
          },
...
```

**Comment by welaaa-sangyeon** [comment]
해상도마다 레이아웃이 다른것에 대해 예시 이미지를 첨부합니다

![kakaotalk_photo_2019-02-01-09-38-40](https://user-images.githubusercontent.com/44987455/52095138-47096200-2605-11e9-8120-65d773b7d30b.jpeg)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

리딩멘토 이미지 교체 관련 내용은 
(https://github.com/smart-learning/design-2.0/issues/38#issuecomment-459345777) 코멘트 확인 부탁드립니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-02-08-0915-design-release.apk 기준

- 최상단 GNB 영역 노출 텍스트 삭제 ('이달의 책' 부분)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-11-1726-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-11-1726-design-release.apk  
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549874072008300)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52710787-8d7e9980-2fd3-11e9-86a8-14714b9ae4de.png)

**Comment by nanuruya** [comment]
강사 썸네일 이미지도 오디오북과 동일한 이슈로 보입니다. contain을 사용할지, cover를 사용할지 결정이 필요할것같습니다. 
이미지 표시영역은 디자인을 기준으로 잡혀있는 상태 입니다. 
디자인과 실제 적용 이미지 크기가 다르게 적용될 경우 미리 알려주시면 좋겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

썸네일 표현되는 방식이 기존 그대로입니다
