### ISSUE TITLE
[상세 공통] 컨텐츠 영역 레이아웃 수정 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#66]
- [x] 본문 텍스트 행간 넓혀 가독성 높임
- [x] 본문 한자 누락 수정
- [x] 행간 넓혀 볼륨 키우기
- [x] 펼칠땐 '더보기' 접을땐 '접기'버튼으로 변경

**Comment by daroong2** [comment]
한자 누락 수정은 범위가 커져서 이슈 따로 작성하겠습니다.
