### ISSUE TITLE
[상세 공통] 컨텐츠영역 저자 레이아웃 수정 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#69]
- [x] 썸네일 이미지 추가 
- [x] 저자 텍스트 본문 위로 이동
![image](https://user-images.githubusercontent.com/3823119/48462073-05dd8f00-e81a-11e8-8dd6-8baafec726e4.png)

**Comment by daroong2** [comment]
썸네일 이미지는 api로 받아오는 이미지를 사용하고 있습니다. 
표시가 안 되는 이미지는 api에서 수정이 되면 표시될 예정입니다.
