### ISSUE TITLE
[메인 > 클래스] 최근재생클래스: 컴포넌트 레이아웃 추가

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#87]
![image](https://user-images.githubusercontent.com/3823119/49355381-a2ed6280-f70a-11e8-9707-5bce411c646d.png)

**Comment by nanuruya** [comment]
[작업 확인 영상 캡쳐 링크]  
https://youtu.be/2AbaChw1xWg

**Comment by welaaa-sangyeon** [comment]
> [welaaa-1.50.047-2019-01-23-1833-design-release.apk] 기준 


- 콤포넌트 사이즈가 우측으로 갈수록 축소
- 플레이 btn 위치

최종 전달 XD 'App_class_메인페이지_190115_confirm2.xd'

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52046240-a2960a00-2589-11e9-988b-cf820bbeed28.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

-컴포넌트 R값이 너무 큽니다. 수치 확인부탁드립니다.

**Comment by nanuruya** [comment]
같은 스타일을 사용하는 컴포넌트 수정할때 같이 수정되면서 Radius 값이 디자인과 달라진것 같습니다.
같은 스타일을 사용하지않도록 업데이트 처리 할 예정입니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
