### ISSUE TITLE
[메인 > 클래스] 클래스 기본 컴포넌트 레이아웃 변경 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#88]
![image](https://user-images.githubusercontent.com/3823119/49355425-e21bb380-f70a-11e8-9b5b-d124fe47751f.png)

**Comment by nanuruya** [comment]
[작업 확인 영상 캡쳐 링크]  
https://youtu.be/qhC5R93MBOk

**Comment by welaaa-sangyeon** [comment]
5-3. R값 미적용
5-4. 썸네일 비율 XD파일에서 확인 (기존에서 세로값 수정됨)
5-5. 타이틀, 강사, 뱃지의 간격 일정하게. XD 참고

![image](https://user-images.githubusercontent.com/44987455/50869568-f03ead00-13f7-11e9-997b-b0ef0e3a6815.png)

--
5-6. 행간 너무 타이트함, XD 참고

![image](https://user-images.githubusercontent.com/44987455/50869581-ffbdf600-13f7-11e9-86ae-d409c2639412.png)

--
5-7. Light 서체인지 확인 요망 (시스템 서체에 따른 사양으로 확인 완료)
5-8. 재생수, 평점, 댓글의 간격이 너무 타이트함 (XD 참고)

![image](https://user-images.githubusercontent.com/44987455/50869599-12d0c600-13f8-11e9-8ab9-cd3fe1cc5ab1.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52047052-8c894900-258b-11e9-8298-40059c2bef92.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
썸네일 하단 강의 타이틀, 강사, 뱃지 사이의 간격은 조정이 되었는지 문의드립니다.
지난주 공유주셨던 버전에서 바뀐건지 잘 모르겠습니다.

**Comment by nanuruya** [comment]
네 조정되었습니다. 2픽셀 차이가 있었습니다.

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52711409-14804180-2fd5-11e9-9628-8e3f3659adeb.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
