### ISSUE TITLE
[메인 > 클래스] 인기클래스 컴포넌트 디자인 수정 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#89]
![image](https://user-images.githubusercontent.com/3823119/49355448-f95aa100-f70a-11e8-86df-01bec3502937.png)

**Comment by nanuruya** [comment]
[작업 확인 영상 캡쳐 링크]  
https://youtu.be/4-FG69NHnT8

**Comment by welaaa-sangyeon** [comment]
> [welaaa-1.50.047-2019-01-23-1833-design-release.apk] 기준

- 첫 시안부터 지금까지 노출갯수가 변경되지 않았던 부분입니다. 다시 한번 변경 요청드립니다.

최종 전달 XD 'App_class_메인페이지_190115_confirm2.xd'

--
![image](https://user-images.githubusercontent.com/44987455/51663666-b7f3bd00-1ffa-11e9-9871-f6901973d055.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52046743-cad23880-258a-11e9-84d0-317bbda7f7a8.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-02-08-0915-design-release.apk 기준

- 아이콘 위치 살짝 이동 부탁드립니다.

![2](https://user-images.githubusercontent.com/44987455/52461783-edc8a200-2bb3-11e9-81ec-d415550200f5.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-11-1726-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-11-1726-design-release.apk  
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549874072008300)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk


@jungon-influential  
- 썸네일을 윌라닷컴의 실시간 인기 클래스에 적용된 것처럼 변경해야할 것 같습니다. 확인 부탁드려요

**Comment by jungon-influential** [comment]
@Unk `"images": {
        "big": ...,
        "list": ...,
        "wide": ...
      },`

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

각각의 컴포넌트 상에서 플레이버튼을 제외한 나머지 영역은 해당 클래스 상세 페이지로 이동되어야 합니다

**Comment by Unk** [comment]
상세 페이지 이동에 대한 내용은 전달 받은 적이 없습니다.. 기존엔 재생만 하게 되어 있었고 디자인 업데이트에 대한 요청만 받아서 처리된 부분입니다.
해당 부분에서의 이동 처리는 복잡한 부분은 아니니 요청하신대로 처리 하도록 하겠습니다.
