### ISSUE TITLE
[메인>클래스] 스와이퍼 적용

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#90]
- [x] 최근 재생 클래스
- [x] 새로 나온 클래스
- [x] 오늘의 인기 클래스
- [x] 000님의 추천 클래스

**Comment by welaaa-sangyeon** [comment]
현재까지 정의된 각 스와이퍼 별 컴포넌트 노출 갯수 정책 공유드립니다.

최근 재생 클래스 - 5개
새로 나온 클래스 - 10개
오늘의 인기 클래스 - 최근 일주일간 가장 많은 재생 시간 기준, 총 15개 노출
OOO님을 위한 추천 클래스 - max 5개 노출
