### ISSUE TITLE
[메인 > 클래스] 섹션 타이틀 레이아웃 수정 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#92]
텍스트 타입
![image](https://user-images.githubusercontent.com/3823119/49357307-2b233600-f712-11e8-9307-23145508be19.png)

텍스트 + 버튼 타입
![image](https://user-images.githubusercontent.com/3823119/49357316-324a4400-f712-11e8-990f-061a3898ddd0.png)

서브타이틀 타입 
![image](https://user-images.githubusercontent.com/3823119/49357319-35453480-f712-11e8-9b31-1a2bcea0f745.png)

**Comment by welaaa-sangyeon** [comment]
타이틀 폰트  스타일/사이즈 변경

(App_class_메인페이지_190115_confirm2.xd)

--
윌라 추천시리즈, 윌라 프리미엄 클래스

![image](https://user-images.githubusercontent.com/44987455/51163576-8df51900-18dd-11e9-8d9a-05f3945d57f5.png)

--
새로 나온 클래스, 오늘의 인기 클래스, 추천 클래스

![image](https://user-images.githubusercontent.com/44987455/51164184-79198500-18df-11e9-89ed-48619d91208d.png)
![image](https://user-images.githubusercontent.com/44987455/51164059-10320d00-18df-11e9-8aeb-1130552f0789.png)
![image](https://user-images.githubusercontent.com/44987455/51164064-13c59400-18df-11e9-8d31-88f25f336e95.png)

**Comment by welaaa-sangyeon** [comment]
190131_1.50.050.apk 기준

폰트 자간 및 상하단 여백 재확인 필요 (모든 타이틀 텍스트 상하단 여백 동일하게 조정 필요)

**Comment by nanuruya** [comment]
welaaa-1.50.049-2019-02-02-1034-design-release 빌드버전에 적용되었습니다.

APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)
