### ISSUE TITLE
[메인 > 오디오] 섹션 타이틀 레이아웃 수정

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#93]

**Comment by welaaa-sangyeon** [comment]
타이틀 폰트 스타일/사이즈 변경

(App_audio_메인페이지_190115_confirm2.xd)

--
매일 책 한권, 윌라 오디오북

![image](https://user-images.githubusercontent.com/44987455/51164395-2096b780-18e0-11e9-9424-8a22d6d6e698.png)
![image](https://user-images.githubusercontent.com/44987455/51164403-25f40200-18e0-11e9-8e41-322802009c2f.png)

--
최근 재생 오디오북, 새로 나온 오디오북, 오늘의 인기 오디오북, 추천 오디오북

![image](https://user-images.githubusercontent.com/44987455/51164412-2db3a680-18e0-11e9-996f-6951555e2134.png)
![image](https://user-images.githubusercontent.com/44987455/51164426-34dab480-18e0-11e9-86e6-dedf871209b3.png)
![image](https://user-images.githubusercontent.com/44987455/51164437-3b692c00-18e0-11e9-9faf-5e248190b301.png)
![image](https://user-images.githubusercontent.com/44987455/51164442-40c67680-18e0-11e9-925a-2dde18b526b3.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

모든 타이틀 텍스트 - 폰트 자간 및 상하단 여백 재확인 필요 (모든 타이틀 텍스트 상하단 여백 동일하게 조정 필요)

**Comment by nanuruya** [comment]
welaaa-1.50.049-2019-02-02-1034-design-release 빌드버전에 적용되었습니다.

APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.049-2019-02-04-2126-design-release.apk 기준

'새로 나온 오디오북' 상단 여백을 '새로 나온 클래스'와 통일

**Comment by Unk** [comment]
`welaaa-1.50.050-2019-02-08-0915-design-release.apk`  
https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549585112015800
