### ISSUE TITLE
[메인 > 오디오북] 최근재생오디오북 레이아웃 추가 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#94]
![image](https://user-images.githubusercontent.com/3823119/49780131-8677a880-fd50-11e8-9407-c1298d2759c6.png)

**Comment by nanuruya** [comment]
[작업 확인 영상 캡쳐 링크]
https://youtu.be/88OQZX34-_0

**Comment by nanuruya** [comment]
[작업 확인 영상 캡쳐 링크]  
https://youtu.be/88OQZX34-_0

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 썸네일 이미지가 중앙정렬이 아니라 top을 기준으로 윗부분이 나오게 해주세요.
- 윌라닷컴의 실시간 오디오북 썸네일을 참고

**Comment by Unk** [comment]
현재 앱에서 이미지를 표시할 때 설정할 수 있는 리사이즈 모드는 세가지 중 하나입니다.

* contain - 레터박스 생김
* cover - 중앙 크롭
* stretch - 비율무시하고 맞춤

**Comment by Unk** [comment]
이미지들이 전부 상단을 사용하는 것을 전제로 만들어지게되나요? 아니면 책 이미지가 사용되나요? 제목이나 사진 등이 잘리는 것 때문이라면 상단 기준으로 크롭을 하면 컨텐츠가 하단 중심으로 있는 이미지는 또 잘못 잘리는 현상이 생기게 되긴 합니다.

**Comment by jungon-influential** [comment]
cover 이미지들은 `contain` 으로 설정해주세요.
이미지 세로 높이로 맞추고 뷰 컨테이너 가운데 정렬이 되면 됩니다.
react-native 에서 `contain` 이 저 요건을 충족한다고 판단됩니다.

**Comment by Unk** [comment]
최근 재생 오디오북의 책 커버 이미지는 contain 으로 변경 하시는거죠?
------
리사이즈 부분은 저희가 초기부터 계속 문의드린 부분인데... 너무 자주 바뀝니다 ㅡㅜ

**Comment by jungon-influential** [comment]
죄송합니다. 제가 확인이 늦었네요.
우선 커버 이미지는 다 contain 으로 맞춰 주세요.
1:7 이미지(기존) 이라면 양 옆으로 여백이 생기는 거 확인 할 거고
1:4 이미지(변경 될) 이라면 꼭 차 보일테고
이 외의 비율이 뭐 있는지 확인해 보려 합니다.

**Comment by nanuruya** [comment]
이미지 비율중에 1:1.6도 있습니다.

**Comment by jungon-influential** [comment]
네 다른 비율도 있을 거라 생각됩니다.
1:6 이면 1:7 보다는 양옆 여백이 적을거고 1:4보다는 많이 남겠죠.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.049-2019-02-15-0646-design-release.apk

하필 전체 오디오북 썸네일에 관한 논의를 해당 이슈에서 하였네요


최근 재생 오디오북만 아래 이미지처럼 width가 꽉차고 top을 기준으로 하단이 크롭되어야 합니다.

![_](https://user-images.githubusercontent.com/44987455/52827503-755c6680-3108-11e9-80ca-94f491da6959.png)

**Comment by Unk** [comment]
크롭시 위치 설정에 대한 옵션은 없습니다.
contain 으로 전체 표시하거나 cover 로 중앙부 크롭을 하거나 입니다.
