### ISSUE TITLE
[메인 > 오디오북] 새로 나온 오디오북 레이아웃 변경 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#95]
![image](https://user-images.githubusercontent.com/3823119/49780195-c8a0ea00-fd50-11e8-9054-b4fe43bd8ae2.png)

**Comment by nanuruya** [comment]
https://youtu.be/wGANm6ZP12o

**Comment by welaaa-sangyeon** [comment]
오디오북 썸네일이 변경되어 UI를 변경하였습니다.

(App_audio_메인페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51240974-3380b900-19c0-11e9-99f5-10ab81c16f9d.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk

--
![default](https://user-images.githubusercontent.com/44987455/52054381-a92f7c00-259f-11e9-8963-b693026e5915.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-02-08-0915-design-release.apk 기준

- 썸네일 Height 값 기준으로 자동 맞춤, 자동 크롭 되어야 하는데 미적용되어 크기가 랜덤으로 보임

![image](https://user-images.githubusercontent.com/44987455/52460761-477a9d80-2baf-11e9-94d2-6dd38836c72f.png)

![image](https://user-images.githubusercontent.com/44987455/52460775-5eb98b00-2baf-11e9-99c7-39f825b53651.png)


App_audio_메인페이지_190116_confirm.xd 참조

**Comment by Unk** [comment]
변경되는 비율에 대해 기존 이미지는 관리자단에서 이미지를 관리자가 변경하거나 배치 작업으로 일괄 변경을 하신다고 들었습니다. 아직 변경되지 않은 이미지에 대해서는 어떻게 처리할지에 대해서는 명확하게 이야기 된 적이 없는 것 같은데요, 세 가지 옵션이 있습니다.

- 비율을 무시하고 찌그러뜨려서 맞춤
  - 장점: 없음
  - 단점: 일러스트나 사진이 들어간 경우 비율이 찌그러져 흉하게 보임
- 크롭
  - 장점: 꽉 채운 화면
  - 단점: 예상치 못한 부분이 잘려나갈 수 있음. 그게 제목이나 사람의 얼굴 등이 될 수도 있음
- 레터박스 생성 (현재 상태)
  - 장점: 이미지가 온전히 보임
  - 단점: 레터박스

일단은 이미지 자체가 다 업데이트 되어야 겠습니다만, 업데이트 되지 않은 이미지는 위의 3가지 옵션 중 하나를 선택하셔야 할 것 같습니다. 내부에서 결정하시고 알려주시죠.

**Comment by welaaa-sangyeon** [comment]
말씀해주신 부분중에는 '크롭'이 맞습니다.

위에 확정해서 말씀드린데로 모든 오디오북 썸네일에는 1:1.4 비율을 적용할 생각입니다.

하여  height 꽉차게  이미지가 적용되고 넘어가는 부분은 자동 크롭되는 것이 맞으며, 가로가 넘어가는 썸네일의 경우는 저희가 확인 후 내부에서 이미지를 교체하고자 합니다.

상세한 의견 감사합니다^-^

**Comment by Unk** [comment]
네 그럼 크롭으로 적용 하도록 하겠습니다.

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-11-1726-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-11-1726-design-release.apk  
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549874072008300)
