### ISSUE TITLE
[ 메인 > 오디오북 ] 오늘의 인기 오디오북 레이아웃 변경 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#96]
![image](https://user-images.githubusercontent.com/3823119/49780222-dd7d7d80-fd50-11e8-8b98-90e426c53c32.png)

**Comment by nanuruya** [comment]
[작업 확인 영상 캡쳐 링크]  
https://youtu.be/frI39u1DojY

**Comment by welaaa-sangyeon** [comment]
오디오북 썸네일이 변경되어 UI를 변경하였습니다.

(App_audio_메인페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51241117-7a6eae80-19c0-11e9-8c3b-50133c53d236.png)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-01-31-0901-design-release.apk 기준

--
![default](https://user-images.githubusercontent.com/44987455/52054422-ca906800-259f-11e9-9e35-912966f72da9.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-02-1034-design-release` 빌드버전에 적용되었습니다.

## APK 확인 링크
welaaa-1.50.049-2019-02-02-1034-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549071732048100)

**Comment by welaaa-sangyeon** [comment]
welaaa-1.50.050-2019-02-08-0915-design-release.apk 기준

- 아이콘 위치가 조금 내려간 것 같습니다. 위로 이동 부탁드립니다.

![2](https://user-images.githubusercontent.com/44987455/52461834-194b8c80-2bb4-11e9-8c89-4ffc97b6c136.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-11-1726-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-11-1726-design-release.apk  
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1549874072008300)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 썸네일에 R값이 잘못 들어간 것 같습니다

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
