### ISSUE TITLE
[메인 > 오디오북] 추천 오디오북 레이아웃 변경 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#97]
![image](https://user-images.githubusercontent.com/3823119/49780237-ed955d00-fd50-11e8-988d-90cbda3462e4.png)

**Comment by welaaa-sangyeon** [comment]
미구현인지 확인 요망

![image](https://user-images.githubusercontent.com/44987455/50870218-6fcd7b80-13fa-11e9-8aef-063cfab2af5d.png)

**Comment by nanuruya** [comment]
3-1: 추가적인 설명이 필요합니다.
3-2: API 에서 보내주는값이 제대로 표시되는 중입니다.

**Comment by welaaa-sangyeon** [comment]
3-1 > 해당 회색 선은 영역을 구분하기 위한 선입니다. (예: 매일책한권 - 윌라 오디오북의 중간 선)
       > 한마디로 widht 꽉차게 부탁드립니다

3-2 > @jungon-influential 김중온 과장님께서 확인 예정입니다

**Comment by jungon-influential** [comment]
`/api/v1.0/cms/main/audiobook` recommend 값이 비어있는 것을 확인했습니다.
내부적으로 협의 될 사항이 있어서 아직 미구현 상태이고 개발진행 하도록 하겠습니다.
그전에 이 부분도 오디오북 포맷으로 필요한 값만 목업데이터로 구성 부탁 드립니다.

```
 recommend 예상 키

  "audiobook_sale",
  "audiobook_type",
  "banner_color",
  "botm",
  "hit_count",
  "id",
  "idx",
  "images",
  "is_bookreview",
  "is_botm",
  "is_exclusive",
  "is_free",
  "is_new",
  "like_count",
  "memo",
  "memo_top",
  "meta",
  "orig_price",
  "pay_key_ios",
  "pay_money",
  "pay_money_ios",
  "play_time",
  "progress",
  "review_count",
  "reviewer_badge",
  "sale_price",
  "star_avg",
  "subtitle",
  "teacher",
  "title",
  "type",
  "url",
  "user_zzim"
```

감사합니다.

**Comment by welaaa-sangyeon** [comment]
오디오북 썸네일이 변경되어 UI를 변경하였습니다.

(App_audio_메인페이지_190116_confirm.xd)

--
![image](https://user-images.githubusercontent.com/44987455/51241189-a68a2f80-19c0-11e9-9fe5-0aefcaa87653.png)

**Comment by welaaa-sangyeon** [comment]
OOO님을 위한 추천 오디오북 영역은 API 이슈로 삭제 부탁드립니다.
아래와 같이 변경해주세요.
(클래스는 그대로 유지)

![image](https://user-images.githubusercontent.com/44987455/51301642-456f6400-1a73-11e9-811c-c1a5b7c87dfa.png)
