### ISSUE TITLE
[메인 > 오디오북] 전체보기 버튼 추가 

### ISSUE THREAD

**Issue by nanuruya** [smart-learning/design-2.0#98]
![image](https://user-images.githubusercontent.com/3823119/49780246-fbe37900-fd50-11e8-9e92-ab334bbd3553.png)

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

- 버튼 외부 상단, 하단 여백을 클래스 페이지와 같게 적용 부탁드립니다.

**Comment by welaaa-sangyeon** [comment]
> welaaa-1.50.050-2019-02-12-1916-design-release.apk

![_](https://user-images.githubusercontent.com/44987455/52711000-172e6700-2fd4-11e9-97e3-d4f95139103c.png)

**Comment by nanuruya** [comment]
`welaaa-1.50.049-2019-02-15-0646-design-release.apk` 빌드버전에 적용되었습니다.

## APK 확인 링크

welaaa-1.50.049-2019-02-15-0646-design-release.apk
(https://influentialsmart.slack.com/archives/GE1C2BEG5/p1550181109083700)
